FLY wire David/force-app/main/default/objects/KYC_Application__c/KYC_Application__c.object-meta.xml
<CustomObject>
    <label>KYC Application</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/objects/KYC_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Application status from Passfort.</description>
    <inlineHelpText>Application applied (submitted but not reviewed for KYC), In Review (KYC in process of reviewing), Approved, Rejected (account declined prior to accepting application), Cancelled (Account Services discontinued after application was initally reviewed)</inlineHelpText>
    <label>Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/Passfort_Webhook_Log__c.object-meta.xml
<CustomObject>
    <label>Passfort Webhook Log</label>
    <nameField>
        <displayFormat>PWL-{0000000}</displayFormat>
        <label>Passfort Webhook Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passfort Webhook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Extracted_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Extracted_Profile_Id__c</fullName>
    <inlineHelpText>Passfort ProfileId extracted from the request body JSON</inlineHelpText>
    <label>Extracted Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message when processing the request.</description>
    <inlineHelpText>Message when processing the request.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Request_body__c.field-meta.xml
<CustomField>
    <fullName>Request_body__c</fullName>
    <description>Request body from webhook.</description>
    <inlineHelpText>Request body from webhook</inlineHelpText>
    <label>Request body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the webhook.</description>
    <inlineHelpText>Request body from webhook</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/classes/PassfortProfileBatchProcessor.cls
public without sharing class PassfortProfileBatchProcessor implements Database.Batchable<String>, Database.AllowsCallouts {
    private List<String> profileIds;
    private String reqBody;
    List<Passfort_Webhook_Log__c> webHookLogs = new List<Passfort_Webhook_Log__c>();

    public PassfortProfileBatchProcessor(Set<String> profileIds, String reqBody) {
        this.profileIds = new List<String>(profileIds);
        this.reqBody = reqBody;
    }

    public List<String> start(Database.BatchableContext bc) {
        return profileIds;
    }

    public void execute(Database.BatchableContext bc, List<String> scope) {
        Set<Account> updatedAccounts = new Set<Account>();
        List<KYC_Application__c> kycApps = new List<KYC_Application__c>();
        
        for (String currentProfileId : scope) {
            Passfort_Webhook_Log__c log = new Passfort_Webhook_Log__c();
            log.Request_body__c = reqBody;
            log.Extracted_Profile_Id__c = currentProfileId;
            try {
                PassfortUtil.PassfortProfileProcessingWrapper wrapper = PassfortUtil.updateAccout(log.Extracted_Profile_Id__c, log);
                log.Status__c = 'Success';
                log.Message__c = wrapper.logMessage;
                if (wrapper.acct != null) {
                    updatedAccounts.add(wrapper.acct);
                }
                if (!wrapper.apps.isEmpty()) {
                    kycApps.addAll(wrapper.apps);
                }
            } catch (PassfortWebhook.RequestBodyException e) {
                System.debug(e.getMessage());
                log.Status__c = 'Error';
                String logMessage = e.getMessage();
                logMessage = logMessage.length() > 131071 ? logMessage.substring(0, 131072) : logMessage;
                log.Message__c = logMessage;
            }
            webHookLogs.add(log);
        }
        System.enqueueJob(new PassfortProfileAsyncProcessor(webHookLogs, updatedAccounts, kycApps));
    }

    public void finish(Database.BatchableContext bc) {}
}