FLY wire David/force-app/main/default/objects/KYC_Application__c/KYC_Application__c.object-meta.xml
<CustomObject>
    <label>KYC Application</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/objects/KYC_Application__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Passfort Identifier for KYC application</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Passfort Identifier for KYC application</inlineHelpText>
    <label>Application ID</label>
    <length>205</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/Passfort_Webhook_Log__c.object-meta.xml
<CustomObject>
    <label>Passfort Webhook Log</label>
    <nameField>
        <displayFormat>PWL-{0000000}</displayFormat>
        <label>Passfort Webhook Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passfort Webhook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/classes/PassfortProfileAsyncProcessor.cls
public without sharing class PassfortProfileAsyncProcessor implements Queueable, Database.AllowsCallouts {
    List<Passfort_Webhook_Log__c> webHookLogs;
    List<Account> updatedAccounts;
    List<KYC_Application__c> kycApps;

    public PassfortProfileAsyncProcessor(List<Passfort_Webhook_Log__c> webHookLogs, Set<Account> updatedAccounts, List<KYC_Application__c> kycApps) {
        this.webHookLogs = webHookLogs;
        this.updatedAccounts = new List<Account>(updatedAccounts);
        this.kycApps = kycApps;
    }

    public void execute(QueueableContext context) {
        if (!webHookLogs.isEmpty()) {
            insert webHookLogs;
        }
        if (!updatedAccounts.isEmpty()) {
            update updatedAccounts;
        }
        if (!kycApps.isEmpty()) {
            upsert kycApps Application_ID__c;
        }        
    }
}