David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Create_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Create_Shipment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Shipment</label>
    <type>Checkbox</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Run_Shipment_Flow__c.field-meta.xml
<CustomField>
    <fullName>Run_Shipment_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Shipment Flow</label>
    <type>Checkbox</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/UpdateRMABatchTest.cls
@isTest

public class UpdateRMABatchTest{

	

    static testmethod void test() {

        
        
            Account a = testDataFactory.createAccount(true);
            RMA__c r = new RMA__c(Create_Shipment__c = true, Run_Shipment_Flow__c = false);
            insert r;
            
        

        Test.startTest();


        UpdateRMABatch upfb = new UpdateRMABatch();
        Database.executeBatch(upfb, 1);
        System.schedule('Scheduled Job 7', '0 0 * * * ?', new UpdateRMABatch());

        Test.stopTest();
        }
}