David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Opportunity__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_RMA_Item_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_RMA_Item_Received__c</fullName>
    <label>Date RMA Item Received</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT( ProductItem__r.Location__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Probe_Model__c.field-meta.xml
<CustomField>
    <fullName>Probe_Model__c</fullName>
    <formula>ProductItem__r.Product_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probe Model</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/RMA_Type__c.field-meta.xml
<CustomField>
    <fullName>RMA_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RMA Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/RMAList.cls
public class RMAList {
    Public List<RMA__c> rmaList{get;set;}
    ID accountID;
    String accountName;
    Account acc;
    public RMAList(ApexPages.StandardController controller) {
        accountID=ApexPages.currentPage().getParameters().get('Id');
        System.debug('-------------------------'+accountID);
        
        
        acc=[Select Name,id From Account where id=:accountID];
        
        if(acc != Null){
            accountName=acc.Name;
        }
        if(accountName !=null){
        rmaList=[Select Name,RMA_Type__c,Location__c,Amount__c,Account_Name__c,ProductItem__c,Probe_Model__c,CreatedDate,Date_RMA_Item_Received__c from RMA__c where Account_Name__c=:accountName ORDER BY CreatedDate DESC];
        }
    }

}