David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Approved_Repairs__c.field-meta.xml
<CustomField>
    <fullName>Approved_Repairs__c</fullName>
    <label>Approved Repairs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Probe_Repair_Activities</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/CreateApprovedRepairsTestClass.cls
@isTest
public class CreateApprovedRepairsTestClass {

    static testmethod void TestCreateApprovedRepairsTest() {
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        RMA__c rma = TestDataFactory.createRMA('Customer Repair Evaluation', true);

        Test.startTest();

        rma.Approved_Repairs__c = 'All Repairs Approved';
        update rma;

        rma.Approved_Repairs__c = 'Cable Replacement';
        update rma;

        Test.stopTest();
    }
}