FLY wire David/force-app/main/default/objects/AccountContactRelation/fields/Billing_Contact_for_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_for_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for SALDEV-1045</description>
    <label>Billing Contact for Account</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to identify this as the official person to send bills to for the associated Client.</description>
    <inlineHelpText>Check to identify this as the official person to send bills to for the associated Client.</inlineHelpText>
    <label>Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Order/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to twin Billing Contact value from Quote to Order</description>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <description>Indicates the approval status of this quote rather than the overall status. Leveraged by the Advanced Approvals package and AA enablement package.</description>
    <inlineHelpText>Indicates the approval status of this quote rather than the overall status</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created from JIRA ticket: BOPI-32.</description>
    <inlineHelpText>Select a Billing Contact related to the Account Hierarchy</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3 AND 4</booleanFilter>
        <errorMessage>Contact must be active and marked as the Billing contact on their Contact record.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Billing_Contact__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select the Billing Contact for this Client. Contact must be active and marked as the Billing contact on their Contact record.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Billing Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/classes/AQS_QuoteExtControllerTests.cls
@isTest
private class AQS_QuoteExtControllerTests {

    @TestSetup
    static void makeData() {
        Database.SaveResult acct = Database.insert(new Account(
            Name = 'Test Account',
            ShippingCountry = 'United States',
            ShippingState = 'MA',
            ShippingStreet = 'Suite 10, 141 Tremont Street',
            ShippingCity = 'Boston',
            ShippingPostalCode = '02111',
            BillingCountry = 'United States',
            BillingState = 'MA',
            BillingStreet = 'Suite 10, 141 Tremont Street',
            BillingCity = 'Boston',
            BillingPostalCode = '02111'
        ));

        Contact testContact = new Contact(
            FirstName = 'Test First Name',
            LastName='Test Last Name',
            Email = 'test@contact.com',
            //Billing_Contact__c = true,
            AccountId = acct.getId()
        );

        insert testContact;
        
        // 3. Query the existing ACR (instead of inserting a new one)
    AccountContactRelation existingAcr = [
        SELECT Id, Roles, Billing_Contact_For_Account__c 
        FROM AccountContactRelation 
        WHERE AccountId = :acct.Id 
        AND ContactId = :testContact.Id 
        LIMIT 1
    ];

    // 4. Update the existing ACR with your required values
    existingAcr.Roles = 'Decision Maker';
    existingAcr.Billing_Contact_For_Account__c = true;
    update existingAcr;

        Opportunity testOppty = new Opportunity(
            AccountId = acct.getId(), 
            Name='Test CPQOpp', StageName='Open',
            CloseDate=Date.today().addDays(30)
        );
        Database.SaveResult oppty = Database.insert(testOppty);
        
        // This satisfies the new Primary Contact Role validation rule
    OpportunityContactRole ocr = new OpportunityContactRole(
        OpportunityId = testOppty.Id,
        ContactId = testContact.Id,
        Role = 'Decision Maker', // Satisfies mandatory role requirement
        IsPrimary = true        // Satisfies 'Primary' requirement
    );
    insert ocr;

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = acct.getId(),
            SBQQ__Opportunity2__c = oppty.getId(),
            SBQQ__StartDate__c = Date.today(),
            SBQQ__EndDate__c = Date.today().addMonths(12)
            //Billing_Contact__c = contact.getId()
        );

        insert testQuote;
    }
    
    @isTest
    static void testSubmit() {
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];
        
        Test.startTest();
        AQS_QuoteExtController con = new AQS_QuoteExtController(new ApexPages.StandardController(quote));
        con.onSubmit();
        quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c WHERE Id = :quote.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('Approved', quote.ApprovalStatus__c);
    }
    
    @isTest
    static void testErrorSubmit() {
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];
        
        Test.startTest();
        AQS_QuoteExtController con = new AQS_QuoteExtController(new ApexPages.StandardController(quote));
        
        // Delete the quote in order to throw an error
        delete quote;
        
        con.onSubmit();
        Test.stopTest();
        
        con.onCancel();
    }
    
    @isTest
    static void testRecall() {
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();
        AQS_QuoteExtController con = new AQS_QuoteExtController(new ApexPages.StandardController(quote));
        con.onRecall();
        quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];
        Test.stopTest();

        System.assertEquals('Recalled', quote.ApprovalStatus__c);
    }
    
    @isTest
    static void testErrorRecall() {
        SBQQ__Quote__c quote = [SELECT ApprovalStatus__c FROM SBQQ__Quote__c LIMIT 1];
        
        Test.startTest();
        AQS_QuoteExtController con = new AQS_QuoteExtController(new ApexPages.StandardController(quote));
        
        // Delete the quote in order to throw an error
        delete quote;
        
        con.onRecall();
        Test.stopTest();
              
        con.onCancel();
    }
}