FLY wire David/force-app/main/default/objects/OpportunityLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>BOPI-460 This is a twinned field from the Quote Line, it is used on the Opportunity Advanced Approval email templates to show a single column with a price regardless of the product Rate Type and Usage Type</description>
    <inlineHelpText>Will show the usage rate if the product rate type is usage based or a price amount if the product rate type is fixed</inlineHelpText>
    <label>Price</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Check_In_Type__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Type__c</fullName>
    <formula>TEXT(ProductItem__r.Check_In_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check In Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Exchange__c.field-meta.xml
<CustomField>
    <fullName>Exchange__c</fullName>
    <formula>ProductItem__r.Product_Name__r.Retail_Pr_Ex__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exchange</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>ProductItem__r.Product2_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Return_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Return_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RMAS</relationshipLabel>
    <relationshipName>RMAS</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Return_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Return_to_Address__c</fullName>
    <formula>TRIM(IF(NOT(ISBLANK(Return_to_Address_Override__c)), Return_to_Address_Override__c, 
if(ISBLANK(Return_to_Account__r.ShippingStreet), &apos;&apos;, Return_to_Account__r.ShippingStreet &amp; &apos; &apos;) 
&amp;
if(ISBLANK(Return_to_Account__r.ShippingCity), &apos;&apos;, Return_to_Account__r.ShippingCity &amp; &apos;, &apos;)
&amp;
if(ISBLANK(Return_to_Account__r.ShippingState), &apos;&apos;, Return_to_Account__r.ShippingState &amp; &apos; &apos;)
&amp;
if(ISBLANK(Return_to_Account__r.ShippingPostalCode), &apos;&apos;, Return_to_Account__r.ShippingPostalCode)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Return to Address</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Vendor_RMA__c.field-meta.xml
<CustomField>
    <fullName>Vendor_RMA__c</fullName>
    <description>An RMA # provided by a vendor we purchased/sourced a product from.</description>
    <label>Vendor RMA</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/CustomShippingFormDetCmpCtrl.cls
public with sharing class CustomShippingFormDetCmpCtrl {

    public String theOppID {get;set;}

    private List<ShippingFormDetailsRow> tableData = new List<ShippingFormDetailsRow>();

    public CustomShippingFormDetCmpCtrl() {
    }

    public List<ShippingFormDetailsRow> gettableData(){
        GH_Logger.debug('the Opp ID: ' + theOppID);

        Map<Id, List<OpportunityLineItem>> prodItemIDToOLIs = new Map<Id, List<OpportunityLineItem>>();

        for (OpportunityLineItem oli : [
                SELECT ProductItem__c, ProductItem__r.Name, ProductItem__r.Asset_Model_No__c,
                        Check_In_Type__c, Exchange__c, Product_Name__c, TotalPrice,
                        Serial_No__c, ProductItem__r.Model_Number__c
                FROM OpportunityLineItem
                WHERE OpportunityId = :theOppID
                AND ProductItem__c != NULL
        ]) {

            if (!prodItemIDToOLIs.containsKey(oli.ProductItem__c)) {
                prodItemIDToOLIs.put(oli.ProductItem__c, new List<OpportunityLineItem>());
            }
            prodItemIDToOLIs.get(oli.ProductItem__c).add(oli);
        }

        GH_Logger.debug('this many ProductItem from OLI to work with: ' + prodItemIDToOLIs.size());

        Map<Id, RMA__c> prodItemIDToRMA = new Map<Id, RMA__c>();

        for (RMA__c r : [
                SELECT ProductItem__c, Name, Return_To_Account__r.Name, Return_To_Address__c, Vendor_RMA__c
                FROM RMA__c
                WHERE Opportunity__c = :theOppID
                AND ProductItem__c IN :prodItemIDToOLIs.keySet()
        ]) {

            if (!prodItemIDToRMA.containsKey(r.ProductItem__c)) {
                prodItemIDToRMA.put(r.ProductItem__c, r);
            }
        }

        GH_Logger.debug('this many ProductItem from RMA to work with: ' + prodItemIDToRMA.size());

        // populate the output data for all the OLIs, adding in the RMAs as (or if) they are found
        for (Id pItemId : prodItemIDToOLIs.keySet()) {

            GH_Logger.debug('Working with OLIs for ProductItem__c: ' + pItemId);

            for (OpportunityLineItem oli : prodItemIDToOLIs.get(pItemId)) {
                GH_Logger.debug('Adding output row for OLI: ' + oli);

                ShippingFormDetailsRow d = new ShippingFormDetailsRow();
                d.assetNum = oli.ProductItem__r.Name;
                d.productName = oli.Product_Name__c;
                d.serialNum = oli.Serial_No__c;
                d.assetModelNum = oli.ProductItem__r.Asset_Model_No__c;
          //      d.assetPrice = '$' + String.valueOf(oli.ProductItem__r.Price__c);
                d.totalPrice = '$' + String.valueOf(oli.TotalPrice);
                d.modelNum = oli.ProductItem__r.Model_Number__c;
                d.exchange = String.valueOf(oli.Exchange__c);

                if (prodItemIDToRMA.containsKey(pItemId)) {
                    GH_Logger.debug('Found an RMA : ' + prodItemIDToRMA.get(pItemId).Name);
                    d.rmaNum = prodItemIDToRMA.get(pItemId).Name;
                    d.retToAcct = prodItemIDToRMA.get(pItemId).Return_To_Account__r.Name;
                    d.retToAddress = prodItemIDToRMA.get(pItemId).Return_To_Address__c;
                    d.vendorrmaNum = prodItemIDToRMA.get(pItemId).Vendor_RMA__c;
                }
                tableData.add(d);
            }
        }

        return tableData;
    }

    public class ShippingFormDetailsRow {

        public String assetNum {get;set;}
        public String productName {get;set;}
        public String serialNum {get;set;}
        public String assetModelNum {get;set;}
   //     public String assetPrice {get;set;}
        public String totalPrice {get;set;}
        public String modelNum {get;set;}
        public String exchange {get;set;}
        public String rmaNum {get;set;}
        public String vendorrmaNum {get;set;}
        public String retToAcct {get;set;}
        public String retToAddress {get;set;}
    }
}