FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_Repair_Approved__c.field-meta.xml
<CustomField>
    <fullName>Date_Repair_Approved__c</fullName>
    <label>Date Repair Approved</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_Repair_Evaluation_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Repair_Evaluation_Sent__c</fullName>
    <label>Date Repair Evaluation Sent</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Field_Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer__c</fullName>
    <formula>TEXT(Opportunity__r.Field_Service_Engineer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field Service Engineer</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Field_Service_Engineer_Email__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer_Email__c</fullName>
    <label>Field Service Engineer Email</label>
    <type>Email</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Field_Service_Engineer_Text__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer_Text__c</fullName>
    <label>Field Service Engineer Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Loaner_Action_Approved__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Action_Approved__c</fullName>
    <label>Loaner Action Approved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>NOT APPROVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Loaner_Action_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Loaner_Action_Approved_By__c</fullName>
    <label>Loaner Action Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Rental_Action_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Rental_Action_Approved_By__c</fullName>
    <label>Rental Action Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Rental_Return_Action_Approved__c.field-meta.xml
<CustomField>
    <fullName>Rental_Return_Action_Approved__c</fullName>
    <label>Rental Return Action Approved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>NOT APPROVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Return_from_Sale_Action_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Return_from_Sale_Action_Approved_By__c</fullName>
    <label>Return from Sale Action Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Return_from_Sale_Approval__c.field-meta.xml
<CustomField>
    <fullName>Return_from_Sale_Approval__c</fullName>
    <label>Return from Sale Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>NOT APPROVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/RMA_Type__c.field-meta.xml
<CustomField>
    <fullName>RMA_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RMA Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Time_Rental_Action_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Rental_Action_Approved__c</fullName>
    <label>Time Rental Action Approved</label>
    <type>DateTime</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Time_Return_from_Sale_Action_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Return_from_Sale_Action_Approved__c</fullName>
    <label>Time Return from Sale Action Approved</label>
    <type>DateTime</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Time_Warranty_Claim_Approved__c.field-meta.xml
<CustomField>
    <fullName>Time_Warranty_Claim_Approved__c</fullName>
    <label>Time Warranty/Loaner Action Approved</label>
    <type>DateTime</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Warranty_Claim_Approved__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claim_Approved__c</fullName>
    <label>Warranty Claim Action Approval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>NOT APPROVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Warranty_Claim_Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claim_Approved_By__c</fullName>
    <label>Warranty Claim Action Approved By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/scratch/next-four-analysis/devdo/force-app/main/default/classes/RMAHelper.cls
/**
* @author Delagate
* @date 4/5/2021
*
* @description
*/

public without sharing class RMAHelper {
    public static void SetEmailandApprovalFields(List<RMA__c> rmas, Map<Id, RMA__c> oldRmas) {
        for(RMA__c rma : rmas) {
            RMA__c oldRMA =  oldRmas.get(rma.Id);
            if(oldRMA.Field_Service_Engineer__c != rma.Field_Service_Engineer__c && rma.Field_Service_Engineer__c != null) {
                List<String> engineer = rma.Field_Service_Engineer__c.split(' ');String secondPart ='';if(engineer.size () >= 2){secondPart = engineer[1];
                }   
                rma.Field_Service_Engineer_Email__c =  rma.Field_Service_Engineer__c.substring(0,1) + secondPart + '@trisonics.com';
                rma.Field_Service_Engineer_Text__c = rma.Field_Service_Engineer__c; 
            }
            //Add check if approved was changed  
            if(oldRMA.Warranty_Claim_Approved__c != rma.Warranty_Claim_Approved__c || oldRMA.Return_From_Sale_Approval__c != rma.Return_From_Sale_Approval__c || 
               oldRMA.Loaner_Action_Approved__c != rma.Loaner_Action_Approved__c || oldRMA.Rental_Return_Action_Approved__c != rma.Rental_Return_Action_Approved__c){
                    SetFieldsonApproval(rma, oldRMA, 'Warranty_Claim_Approved__c', 'Warranty_Claim_Approved_By__c', 'Time_Warranty_Claim_Approved__c');
            		SetFieldsonApproval(rma, oldRMA, 'Return_from_Sale_Approval__c', 'Return_from_Sale_Action_Approved_By__c', 'Time_Return_from_Sale_Action_Approved__c');
            		SetFieldsonApproval(rma, oldRMA, 'Loaner_Action_Approved__c', 'Loaner_Action_Approved_By__c', 'Time_Warranty_Claim_Approved__c');
            		SetFieldsonApproval(rma, oldRMA, 'Rental_Return_Action_Approved__c', 'Rental_Action_Approved_By__c', 'Time_Rental_Action_Approved__c');
                   
               }
            
        }
    }
    
    //This was not updating the opp. Added code into RMATriggerHandler. This may have caused an extra loop.
    /*public static void AssignDatetoOpp(List<RMA__c> rmas) {
        Map<Id, RMA__c> oppRMAMap = new Map<Id, RMA__c>();
        for(RMA__c rma : rmas) {
            if(rma.RMA_Type__c == 'Customer Repair Evaluation' && rma.Date_Repair_Approved__c != null && rma.Date_Repair_Evaluation_Sent__c != null && rma.Opportunity__r.Date_Repair_Evaluation_Sent__c == null && rma.Opportunity__r.Date_Repair_Approved__c == null) {
                oppRMAMap.put(rma.Opportunity__c, rma);
            }
        }
        List<Opportunity> opps = [SELECT Date_Repair_Evaluation_Sent__c, Date_Repair_Approved__c
                                        FROM Opportunity
                                        WHERE Id in: oppRMAMap.keyset()];
        for(Opportunity opp : opps) {
            RMA__c thisRMA = oppRMAMap.get(opp.Id);opp.Date_Repair_Approved__c = thisRMA.Date_Repair_Approved__c;opp.Date_Repair_Evaluation_Sent__c = thisRMA.Date_Repair_Evaluation_Sent__c;
        }
    }*/
    private static RMA__c SetFieldsonApproval(RMA__c rma, RMA__c oldRMA, string fieldName, string approvedByField, string approvedDateField) {
        if (rma.get(fieldName) != null && oldRMA.get(fieldName) != rma.get(fieldName)){
            rma.put(approvedDateField,DateTime.now());rma.put(approvedByField,UserInfo.getFirstName() + ' ' + UserInfo.getLastName());
        }
        return rma;
    }
    
    
}