FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Customer_Expectation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Expectation__c</fullName>
    <label>Customer Expectation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer wants Equipment Back</fullName>
            </value>
            <value>
                <fullName>Customer Does Not want Equipment Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_RMA_Item_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_RMA_Item_Received__c</fullName>
    <label>Date RMA Item Received</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Probe_Type__c.field-meta.xml
<CustomField>
    <fullName>Probe_Type__c</fullName>
    <formula>ProductItem__r.Probe_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probe Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Quality_Issue_Notes__c.field-meta.xml
<CustomField>
    <fullName>Quality_Issue_Notes__c</fullName>
    <label>Quality Issue Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Shipping_FROM_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_FROM_Location__c</fullName>
    <formula>TEXT(Opportunity__r.Shipping_FROM_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping FROM Location</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/RMAListTest.cls
@isTest
private class RMAListTest{

    static testmethod void TestRMAListTest1() {

        User theUser;
        try{
            theUser = [SELECT Id FROM User WHERE alias = 'dtrog' AND isActive = TRUE LIMIT 1];
        } catch(Exception e){
            System.assert(false, 'Unable to find a user to RunAs.  Looking for Alias of dtrog');
        }

        System.runAs(theUser) {

        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', false);
        pro.Probe_Type__c = 'Sector';
        pro.Family = 'Ultrasound Part';
        insert pro;
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        Account acc = TestDataFactory.createAccount(true);
        Opportunity opp = TestDataFactory.createOpportunity('Sales Opportunity', acc.Id, false);
        opp.Name = 'oppname2';
        opp.Amount = null;
        opp.StageName = 'Closed Won';
        opp.Shipping_FROM_Location__c = 'Fishers, IN';
        opp.CloseDate = system.today();
        insert opp;

        Test.startTest();

            RMA__c rma = TestDataFactory.createRMA('Warranty Claim', false);
            rma.ProductItem__c = pi.Id;
            rma.Opportunity__c = opp.Id;
            rma.Customer_Expectation__c = 'Customer wants Equipment Back';
            rma.Date_RMA_Item_Received__c = system.today() - 2;
            rma.Quality_Issue_Notes__c = 'Bad image';

            System.debug('TEST: start of test');
            insert rma;
            Test.setCurrentPageReference(new PageReference('Page.RMAList'));
            System.currentPageReference().getParameters().put('id', acc.id);
            ApexPages.StandardController sc = new ApexPages.standardController(acc);
            RMAList rm = new RMAList(sc);

            Test.stopTest();
        }

        System.debug('TEST: end of test');
    }
}