FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Check_In_Type__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Type__c</fullName>
    <formula>TEXT(ProductItem__r.Check_In_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Check In Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Other_Notes__c.field-meta.xml
<CustomField>
    <fullName>Other_Notes__c</fullName>
    <label>Other Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Shipping_FROM_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_FROM_Location__c</fullName>
    <formula>TEXT(Opportunity__r.Shipping_FROM_Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping FROM Location</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Billable_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Billable_Work_Order__c</fullName>
    <label>Billable Work Order</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RMA related to a warranty claim work order</description>
    <label>RMA</label>
    <referenceTo>RMA__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Warranty_Claim_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Shipping_FROM_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_FROM_Location__c</fullName>
    <label>Shipping FROM Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Facility</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/recordTypes/UltraSound.recordType-meta.xml
<RecordType>
    <fullName>UltraSound</fullName>
    <active>true</active>
    <label>UltraSound</label>
</RecordType>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/CustomShippingFormDetCmpCtrlTest.cls
@IsTest
private class CustomShippingFormDetCmpCtrlTest {
    @IsTest
    static void simpletestOpp() {

        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        Opportunity opp = TestDataFactory.createOpportunity('Probe Sales Opportunity', null, false);
        opp.StageName = 'Prospecting';
        opp.Shipping_FROM_Location__c = 'Fishers, IN';
        insert opp;

        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, false);
        pi.Other_Notes__c='Cable needs cleaned';
        pi.Check_In_Type__c = 'Purchase';
        pi.PO_Number__c = '1234';
        pi.Purchasing_Opportunity__c = opp.Id;
        pi.Other_Notes__c = 'Cable needs cleaned';
        pi.Repair_Due_Date__c = system.today();
        pi.Asset_Model_No__c = '49dj3l';
        insert pi;

        RMA__c rma = TestDataFactory.createRMA('Customer Repair Evaluation', false);
        rma.ProductItem__c = pi.Id;
        insert rma;

        PricebookEntry pbe = TestDataFactory.createPricebookEntry(pro.Id, true);

        System.assertNotEquals(null, pbe, 'PriceBookEntry was not created');

        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.ProductItem__c = pi.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.Quantity = 1;
        oli.UnitPrice = 5;
        insert oli;

        Test.startTest();
        System.debug('TEST: start of the test');
        CustomShippingFormDetCmpCtrl r = new CustomShippingFormDetCmpCtrl();
        r.theOppID = opp.Id;
        List<CustomShippingFormDetCmpCtrl.ShippingFormDetailsRow> res = r.gettableData();
        Test.stopTest();
        System.debug('TEST: end of the test');
        System.assertNotEquals(null, res, 'gettableData() did not return anything');

    }
    @isTest
    static void simpletestWO() {

        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        Opportunity opp = TestDataFactory.createOpportunity('Probe Sales Opportunity', null, false);
        opp.StageName = 'Prospecting';
        opp.Shipping_FROM_Location__c = 'Fishers, IN';
        insert opp;

        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, false);
        pi.Other_Notes__c='Cable needs cleaned';
        pi.Check_In_Type__c = 'Purchase';
        pi.PO_Number__c = '1234';
        pi.Purchasing_Opportunity__c = opp.Id;
        pi.Other_Notes__c = 'Cable needs cleaned';
        pi.Repair_Due_Date__c = system.today();
        insert pi;

        RMA__c rma = TestDataFactory.createRMA('Customer Repair Evaluation', false);
        rma.ProductItem__c = pi.Id;
        insert rma;

        PricebookEntry pbe = TestDataFactory.createPricebookEntry(pro.Id, true);

        System.assertNotEquals(null, pbe, 'PriceBookEntry was not created');

        Schema.WorkOrder WO = new Schema.WorkOrder(Opportunity__c = opp.id, Billable_Work_Order__c = 1000);
        insert WO;
        
        Schema.WorkOrderLineItem WOLineItem = new Schema.WorkOrderLineItem(WorkOrderID = WO.id, Status = 'NEW', Part_Used__c = pi.id);
        insert WOLineItem;
        

        Test.startTest();
        System.debug('TEST: start of the test');
        CustomShippingFormDetailsWOCtrl r = new CustomShippingFormDetailsWOCtrl();
        r.theWOID = WO.Id;
        List<CustomShippingFormDetailsWOCtrl.ShippingFormDetailsRow> res = r.gettableData();
        Test.stopTest();
        System.debug('TEST: end of the test');
        System.assertNotEquals(null, res, 'gettableData() did not return anything');

    }
}