FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/P_ServiceContractTriggerHandlerTest.cls
@isTest
public class P_ServiceContractTriggerHandlerTest {
    
    static testmethod void CaseCreationTest() {
            Account acct = TestDataFactory.createAccount(true); 
        
        	Opportunity opp = TestDataFactory.createOpportunity('Probe Sales Opportunity', acct.Id, true);
       
        	Test.startTest();
        
            ServiceContract sc = new ServiceContract(Name = 'Test', AccountId = acct.id, Opportunity__c = opp.id, Field_Service_Engineers__c = 'Hobie Sears', StartDate = date.today(), EndDate = date.Today() + 365);
           
            insert sc;
    
            Test.stopTest();
            
    }

}