FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Approved_Repairs__c.field-meta.xml
<CustomField>
    <fullName>Approved_Repairs__c</fullName>
    <label>Approved Repairs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Probe_Repair_Activities</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Probe_Type__c.field-meta.xml
<CustomField>
    <fullName>Probe_Type__c</fullName>
    <formula>ProductItem__r.Probe_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Probe Type</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>RMAS</relationshipLabel>
    <relationshipName>RMAS</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/P_RMATriggerHandlerTest2.cls
/**
 * @author Delegate
 * @date 7/21/2021
 *
 * @description Breaking out of P_RMATriggerHandlerTest
 */
@IsTest
public with sharing class P_RMATriggerHandlerTest2 {

    @TestSetup
    static void makeData() {

        List<Account> accts = TestDataFactory.createAccountsWithContacts(1, 1);
        User u = TestDataFactory.createUser('Adam', 'Walter', true);

        Opportunity opp = TestDataFactory.createOpportunity(
            'Lost Probe Opportunity',
            accts[0].Id,
            true
        );

        Contact con = [
            SELECT Id
            FROM Contact
            LIMIT 1
        ];

        TestDataFactory.createOpportunityContactRole(
            opp.Id,
            con.Id,
            true,
            'Business User',
            true
        );

        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', false);
        pro.Probe_Type__c = 'Linear';
        insert pro;

        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);

        Work_Order__c w = TestDataFactory.createWorkOrder(
            'Repair Work Order',
            pi.Id,
            false
        );
        insert w;

        RMA__c rma = TestDataFactory.createRMA(
            'Customer Repair Evaluation',
            false
        );
        rma.Opportunity__c = opp.Id;
        // rma.ProductItem__c = pi.Id;
        rma.Approved_Repairs__c = null;
        rma.OwnerId = u.Id;
        insert rma;

        RMA__c rma1 = [
            SELECT OwnerId
            FROM RMA__c
            LIMIT 1
        ];
        System.debug(rma1);
    }

    @IsTest
    static void testAddProductItem() {
        Test.startTest();

        RMA__c rma = [
            SELECT Contact_Name__c
            FROM RMA__c
            LIMIT 1
        ];

        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', false);
        pro.Probe_Type__c = 'Linear';
        insert pro;

        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        rma.ProductItem__c = pi.Id;
        update rma;

        Test.stopTest();
    }

    @IsTest
    public static void TestContactNameIsNull() {
        Test.startTest();

        RMA__c rma = [
            SELECT Contact_Name__c
            FROM RMA__c
            LIMIT 1
        ];
        rma.Contact_Name__c = null;
        update rma;

        Test.stopTest();
    }

    @IsTest
    public static void TestApprovedRepairsChanged() {
        Test.startTest();

        RMA__c rma = [
            SELECT Contact_Name__c
            FROM RMA__c
            LIMIT 1
        ];
        rma.Approved_Repairs__c = 'Cable Replacement';
        update rma;

        Test.stopTest();
    }
}