FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Customer_Expectation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Expectation__c</fullName>
    <label>Customer Expectation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer wants Equipment Back</fullName>
            </value>
            <value>
                <fullName>Customer Does Not want Equipment Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_Last_Test_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_Test_Completed__c</fullName>
    <label>Date Last Test Completed</label>
    <type>DateTime</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_Loaner_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Date_Loaner_Shipped__c</fullName>
    <label>Date Loaner Shipped</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_Repair_Approved__c.field-meta.xml
<CustomField>
    <fullName>Date_Repair_Approved__c</fullName>
    <label>Date Repair Approved</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Date_RMA_Item_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_RMA_Item_Received__c</fullName>
    <label>Date RMA Item Received</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Quality_Issue_Notes__c.field-meta.xml
<CustomField>
    <fullName>Quality_Issue_Notes__c</fullName>
    <label>Quality Issue Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Tracking_number_of_RMA_Item_Received__c.field-meta.xml
<CustomField>
    <fullName>Tracking_number_of_RMA_Item_Received__c</fullName>
    <label>Tracking # of RMA Item Received</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/RmaUpdate_TestClass.cls
@isTest
private class RmaUpdate_TestClass{

    static testmethod void TestRMAUpdateTest1() {
        Pricebook2 pricebookstd = new Pricebook2(Name = 'Standard Price Book', isActive = true);
        //ProboCommonUtils.getStdPricebookId();
        insert pricebookstd;
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        Opportunity o = TestDataFactory.createOpportunity('Sales Opportunity', null, true);

        system.debug('#### pi ' + pi);

        Test.startTest();

        RMA__c rma = TestDataFactory.createRMA('Warranty Claim', false);
        rma.ProductItem__c = pi.Id;
        rma.Opportunity__c = o.Id;
        rma.Customer_Expectation__c = 'Customer wants Equipment Back';
        rma.Date_RMA_Item_Received__c = system.today() - 20;
        rma.Date_Loaner_Shipped__c = system.today() - 10;
        rma.Quality_Issue_Notes__c = 'Bad image';
        rma.Tracking_number_of_RMA_Item_Received__c = '489561700';
        insert rma;

        Test.stopTest();
    }

    static testmethod void TestRMAUpdateTest2() {
        Pricebook2 pricebookstd = new Pricebook2(Name = 'Standard Price Book', isActive = true);
        //ProboCommonUtils.getStdPricebookId();
        insert pricebookstd;
        Opportunity o = TestDataFactory.createOpportunity('Sales Opportunity', null, true);
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);

        Test.startTest();

        RMA__c rma = TestDataFactory.createRMA('Loaner Return', false);
        rma.ProductItem__c = pi.Id;
        rma.Opportunity__c = o.Id;
        rma.Quality_Issue_Notes__c = 'Bad image';
        rma.Tracking_number_of_RMA_Item_Received__c = '489561700';
        rma.Date_Loaner_Shipped__c = system.today() - 10;
        insert rma;

        rma.Date_RMA_Item_Received__c = system.today() - 1;
        update rma;

        Test.stopTest();
    }

    static testmethod void TestRMAUpdateTest3() {
        Pricebook2 pricebookstd = new Pricebook2(Name = 'Standard Price Book', isActive = true);
        //ProboCommonUtils.getStdPricebookId();
        insert pricebookstd;
        Opportunity o = TestDataFactory.createOpportunity('Sales Opportunity', null, true);
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);

        Test.startTest();

        RMA__c rma = TestDataFactory.createRMA('Customer Repair Evaluation', false);
        rma.ProductItem__c = pi.Id;
        rma.Opportunity__c = o.Id;
        rma.Date_RMA_Item_Received__c = system.today() - 20;
        rma.Date_Loaner_Shipped__c = system.today() - 10;
        rma.Date_Repair_Approved__c = system.today() - 5;
        rma.Date_Last_Test_Completed__c = system.today();
        rma.Tracking_number_of_RMA_Item_Received__c = '489561700';
        insert rma;

        rma.ProductItem__c = pi.id;
        update rma;

        Test.stopTest();
    }
}