FLY wire David/force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won. Will be entered in Admin for Portal auto creation.</description>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Opportunity ID used to Identify this Opportunity. Should be provided to Onboarding Team once Opportunity is Closed Won.</inlineHelpText>
    <label>Opportunity #</label>
    <type>AutoNumber</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For HC Partners. When Account (Contract) is with Partner, fill in what HC account this opportunity is for. BOPI-451 Filled in by User, used in Flow to auto fill in Quote Line Ship To Account field.</description>
    <inlineHelpText>Equals the Opp Account, unless the Opp is contracted with a Partner, in which case it&apos;s the serviced Account</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/OpportunityLineItem/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/RMA__c.object-meta.xml
<CustomObject>
    <label>RMA</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>RMA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Field_Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer__c</fullName>
    <formula>TEXT(Opportunity__r.Field_Service_Engineer__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Field Service Engineer</label>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/RMA__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMA Item Asset #</label>
    <referenceTo>ProductItem__c</referenceTo>
    <relationshipLabel>RMA</relationshipLabel>
    <relationshipName>RMA</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Field_Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer__c</fullName>
    <label>Field Service Engineer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trisonics_Field_Service_Engineers</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RMA related to a warranty claim work order</description>
    <label>RMA</label>
    <referenceTo>RMA__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Warranty_Claim_Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Ship_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Account__c</fullName>
    <label>Ship to Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/recordTypes/UltraSound.recordType-meta.xml
<RecordType>
    <fullName>UltraSound</fullName>
    <active>true</active>
    <label>UltraSound</label>
</RecordType>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/NewStandardWorkOrderTest.cls
@isTest
public class NewStandardWorkOrderTest {

    @testSetup
    static void setup() {
        Account acc = TestDataFactory.createAccount(false);
        acc.Field_Service_Engineer__c = 'Hobie Sears';
        acc.Standard_Warranty_Length__c = '6 Months';
        acc.Lead_Source__c = 'Referral';
        acc.Name = 'Probo Medical';
        insert acc;
        Contact con = new Contact(LastName='Doe', FirstName='John', AccountId=acc.Id);
        insert con;
        Opportunity opp = TestDataFactory.createOpportunity('Probe Sales Opportunity', acc.Id, false);
        opp.StageName = 'Verbal Acceptance';
        opp.Attention__c = 'TEST';
        opp.Ship_To_Account__c = 'TEST';
        insert opp;
        ServiceContract SC = new ServiceContract(Name = 'Test', Opportunity__c = opp.id);
        insert SC;
        WorkOrder WO = new WorkOrder(Opportunity__c = opp.id, ServiceContractId = SC.id);
        insert WO;
        RMA__c RMARecord = new RMA__c(Opportunity__c = opp.id);
        insert RMARecord;
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', false);
        pro.Functionally_Good_Probes__c = 190;
        insert pro;
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry(pro.Id, true);
        OpportunityLineItem oli = TestDataFactory.createOpportunityLineItem(opp.Id, pbe.Id, pi.Id, true);
    }
    
    static testmethod void TestWOFromOpportunity() {
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
		
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
        ApexPages.currentPage().getParameters().put('id', o.id);
        NewStandardWorkOrder tester = new NewStandardWorkOrder(sc);
        tester.newStdWorkOrder();
       
         
        Test.stopTest();
        
    }
    
    static testmethod void TestWOFromServiceContract() {
        ServiceContract SCRecord = [SELECT Id FROM ServiceContract LIMIT 1];

        Test.startTest();
		
        ApexPages.StandardController sc = new ApexPages.StandardController(SCRecord);
        ApexPages.currentPage().getParameters().put('id', SCRecord.id);
        NewStandardWorkOrder tester = new NewStandardWorkOrder(sc);
        tester.newStdWorkOrder();
       
         
        Test.stopTest();
        
    }
    
    static testmethod void TestWOFromRMA() {
        RMA__c RMARecord = [SELECT Id FROM RMA__c LIMIT 1];

        Test.startTest();
		
        ApexPages.StandardController sc = new ApexPages.StandardController(RMARecord);
        ApexPages.currentPage().getParameters().put('id', RMARecord.id);
        NewStandardWorkOrder tester = new NewStandardWorkOrder(sc);
        tester.newStdWorkOrder();
       
         
        Test.stopTest();
        
    }
    
    static testmethod void TestWOFromWO() {
        WorkOrder WORecord = [SELECT Id FROM WorkOrder LIMIT 1];

        Test.startTest();
		
        ApexPages.StandardController sc = new ApexPages.StandardController(WORecord);
        ApexPages.currentPage().getParameters().put('id', WORecord.id);
        NewStandardWorkOrder tester = new NewStandardWorkOrder(sc);
        tester.newStdWorkOrder();
       
         
        Test.stopTest();
        
    }
}