David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/All_chords_and_cables_intact_no_Frays__c.field-meta.xml
<CustomField>
    <fullName>All_chords_and_cables_intact_no_Frays__c</fullName>
    <label>All chords and cables intact (no Frays)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Options_for_PMR_Form</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Service_Report_Number__c.field-meta.xml
<CustomField>
    <fullName>Service_Report_Number__c</fullName>
    <label>Service Report Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Work_Order_PDF_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_PDF_Type__c</fullName>
    <label>Work Order PDF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Service Report</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance Report</fullName>
            </value>
            <value>
                <fullName>Service Report Form</fullName>
            </value>
            <value>
                <fullName>Trophon PM Form</fullName>
            </value>
            <value>
                <fullName>PPM-SRF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/WorkOrderEntryMergeTest.cls
@isTest
public class WorkOrderEntryMergeTest {
    @isTest static void XeCurrencyCalloutTest(){
         
        List<WorkOrder> wotoinsert = new List<WorkOrder>();
        List<Id> woIds = new List<Id>();
		WorkOrder wo = new WorkOrder(Work_Order_PDF_Type__c = 'Field Service Report');
        wotoinsert.add(wo);
        WorkOrder wo2 = new WorkOrder(All_chords_and_cables_intact_no_Frays__c= 'Pass', Work_Order_PDF_Type__c='Preventative Maintenance Report');
        wotoinsert.add(wo2);
        insert wotoinsert;
        
        system.debug('wotoinsert: ' + wotoinsert);
        
        WorkOrder wo1 = [SELECT WorkOrderNumber,Work_Order_PDF_Type__c FROM WorkOrder WHERE id =: wo.id];
        WorkOrder wo3 = [SELECT WorkOrderNumber,Work_Order_PDF_Type__c FROM WorkOrder WHERE id =: wo2.id];
       	woIds.add(wo1.id);   
        woIds.add(wo3.id);  
        system.debug('wo1 number: ' + wo1.WorkOrderNumber);
        
        wo2.Service_Report_Number__c = wo1.WorkOrderNumber;
        update wo2;               
        
        Test.startTest();
        WorkOrderPDFGenerator.getWorkOrderPDF(woIds);
        WorkOrderPDFGenerator.getWorkOrderPDF(woIds);
        WorkOrderEntryMerge sh1 = new WorkOrderEntryMerge();
		String sch = '0 0 2 * * ?'; 
		system.schedule('Test Territory Check', sch, sh1); 
        Test.stopTest();
        
    }


}