David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Billable_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Billable_Work_Order__c</fullName>
    <label>Billable Work Order</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Work_Order_PDF_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_PDF_Type__c</fullName>
    <label>Work Order PDF Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Service Report</fullName>
            </value>
            <value>
                <fullName>Preventative Maintenance Report</fullName>
            </value>
            <value>
                <fullName>Service Report Form</fullName>
            </value>
            <value>
                <fullName>Trophon PM Form</fullName>
            </value>
            <value>
                <fullName>PPM-SRF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/recordTypes/UltraSound.recordType-meta.xml
<RecordType>
    <fullName>UltraSound</fullName>
    <active>true</active>
    <label>UltraSound</label>
</RecordType>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/P_ServiceWorkOrderTriggerTest.cls
@isTest
private class P_ServiceWorkOrderTriggerTest {

    static testMethod void mytest(){
        Account acc = TestDataFactory.createAccount(true);
        ServiceContract SC = new ServiceContract(name='TEST', AccountId = acc.id, Contract_Billing__c = 'Annual', Field_Service_Engineers__c = 'Hobie Sears', StartDate = date.Today() - 1, EndDate = date.Today() + 1, Coverage_Type__c = 'PM');
        insert SC;
        WorkOrder WO = new WorkOrder(/*ServiceContractID = SC.id,*/ Billable_Work_Order__c = 1000, AccountId = acc.id, Ship_Date__c = date.Today(), Tracking_Number__c = '123', Serial_Number__c = '111');
        insert WO;
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        WorkOrderLineItem WOLineItem = new WorkOrderLineItem(WorkOrderID = WO.id, Status = 'NEW', Part_Used__c = pi.id);
        insert WOLineItem;
        
        //delete WOLineItem;
    }
    
    static testMethod void mytest2(){
        Account acc = TestDataFactory.createAccount(true);
        ServiceContract SC = new ServiceContract(name='TEST', AccountId = acc.id, Contract_Billing__c = 'Annual', Field_Service_Engineers__c = 'Hobie Sears', 
                                                 StartDate = date.Today() - 1, EndDate = date.Today() + 1);
        insert SC;
        
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        Test.startTest();
        WorkOrder WO = new WorkOrder(ServiceContractID = SC.id, Billable_Work_Order__c = 1000, AccountId = acc.id, Status = 'Completed', Work_Order_PDF_Type__c = 'Preventative Maintenance Report');
        insert WO;
        
        WorkOrderLineItem WOLineItem = new WorkOrderLineItem(WorkOrderID = WO.id, Status = 'NEW', Part_Used__c = pi.id);
        insert WOLineItem;
        system.debug('THIS IS THE WO IN THE TEST >>> ' + WO);
        PageReference pRef = Page.SendEmailWorkOrderPDF;
            Test.setCurrentPage(pRef);
            ApexPages.currentPage().getParameters().put('id',WO.Id);
            ApexPages.StandardController sc2 = new ApexPages.StandardController(WO);
            EmailWorkOrderPDF newWO = new EmailWorkOrderPDF(sc2);
        system.debug('THIS IS THE NEW WO PAGE REF >>> ' + newWO);
            newWO.sendEmail();
        delete WOLineItem;
        Test.stopTest();
    }
    
    static testMethod void mytest3(){
        Account acc = TestDataFactory.createAccount(true);
        ServiceContract SC = new ServiceContract(name='TEST', AccountId = acc.id, Contract_Billing__c = 'Annual', Field_Service_Engineers__c = 'Hobie Sears', 
                                                 StartDate = date.Today() - 1, EndDate = date.Today() + 1);
        insert SC;
        
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        Test.startTest();
        WorkOrder WO = new WorkOrder(ServiceContractID = SC.id, Billable_Work_Order__c = 1000, AccountId = acc.id, Status = 'Completed', Work_Order_PDF_Type__c = 'Preventative Maintenance Report');
        insert WO;
        list<WorkOrder> WOList = new List<WorkOrder>();
        WOList.add(WO);
        WorkOrderLineItem WOLineItem = new WorkOrderLineItem(WorkOrderID = WO.id, Status = 'NEW', Part_Used__c = pi.id);
        insert WOLineItem;
        
        EmailWorkOrderPDF.sendPDFEmail(WOList);
       
        Test.stopTest();
    }
    
    static testMethod void mytest4(){
        Account acc = TestDataFactory.createAccount(true);
        ServiceContract SC = new ServiceContract(name='TEST', AccountId = acc.id, Contract_Billing__c = 'Annual', Field_Service_Engineers__c = 'Hobie Sears', StartDate = date.Today() - 1, EndDate = date.Today() + 1, Coverage_Type__c = 'PM');
        insert SC;
        WorkOrder WO = new WorkOrder(/*ServiceContractID = SC.id,*/ Billable_Work_Order__c = 1000, AccountId = acc.id, Serial_Number__c = '111');
        insert WO;
        Product2 pro = TestDataFactory.createProduct('Ultrasound Probe', true);
        
        ProductItem__c pi = TestDataFactory.createProductItem(pro.Id, true);
        WorkOrderLineItem WOLineItem = new WorkOrderLineItem(WorkOrderID = WO.id, Status = 'NEW', Part_Used__c = pi.id);
        insert WOLineItem;
        
        WO.Ship_Date__c = date.Today();
        WO.Tracking_Number__c = '123';
        update WO;
    }
}