David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Parts</fullName>
            </value>
            <value>
                <fullName>Call Out - Major Fault</fullName>
            </value>
            <value>
                <fullName>Call Out - Recurring Fault</fullName>
            </value>
            <value>
                <fullName>Call Out - Return Visit</fullName>
            </value>
            <value>
                <fullName>Call Out - Routine Fault</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Out for Repair</fullName>
            </value>
            <value>
                <fullName>Pending Customer Authorisation</fullName>
            </value>
            <value>
                <fullName>Pending Customer Response</fullName>
            </value>
            <value>
                <fullName>Pre Inspection Visit</fullName>
            </value>
            <value>
                <fullName>Probe Exchange</fullName>
            </value>
            <value>
                <fullName>Probe Repair</fullName>
            </value>
            <value>
                <fullName>Quote Required</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Routine</fullName>
            </value>
            <value>
                <fullName>Sale Preparation</fullName>
            </value>
            <value>
                <fullName>Service Follow Up</fullName>
            </value>
            <value>
                <fullName>System Update</fullName>
            </value>
            <value>
                <fullName>Tech Support</fullName>
            </value>
            <value>
                <fullName>Tech Support – Recurring fault</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Workshop - Awaiting Parts</fullName>
            </value>
            <value>
                <fullName>Workshop - Pending Arrival</fullName>
            </value>
            <value>
                <fullName>Workshop - Pending Customer Approval</fullName>
            </value>
            <value>
                <fullName>Solved by Tech Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Reported_Symptoms__c.field-meta.xml
<CustomField>
    <fullName>Reported_Symptoms__c</fullName>
    <label>Reported Symptoms</label>
    <type>TextArea</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Service_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Completed_Date__c</fullName>
    <label>Service Completed Date</label>
    <type>DateTime</type>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Shipping_FROM_Location__c.field-meta.xml
<CustomField>
    <fullName>Shipping_FROM_Location__c</fullName>
    <label>Shipping FROM Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Facility</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/UKBusinessHoursTest.cls
@isTest(SeeAllData = True)
public class UKBusinessHoursTest {
    static testMethod void Main_Test(){
        ServiceContract sc = new ServiceContract();
        sc.RecordTypeID = '0125b000000LWZGAA4';
        sc.Name = 'SC Test Contract';
        sc.AccountId = '001U000000pNlq7IAC';
        sc.Coverage_Type__c  = 'Warranty';
        sc.Modalities__c = 'CT';
        sc.CurrencyIsoCode = 'EUR';
        sc.Contract_Billing__c = 'Monthly';
        
        insert sc;
        
        WorkOrder wo = new WorkOrder();
        wo.RecordTypeID='0125b000000LW89AAG';
        wo.Status= 'New';
        wo.Priority= 'Low';
        wo.Classification__c= 'Out for Repair';
        wo.StartDate = system.now()-5;
        wo.Shipping_FROM_Location__c = 'Bristol, UK';
        wo.Reported_Symptoms__c = 'Symptoms';
        wo.CurrencyIsoCode = 'EUR';
        wo.ServiceContractId = sc.id;
        
        insert wo;
        
        test.startTest();
        wo.Service_Completed_Date__c = system.now();
        update wo;        
        test.stopTest();
    }
}