David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Field_Service_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Field_Service_Engineer__c</fullName>
    <label>Field Service Engineer</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trisonics_Field_Service_Engineers</valueSetName>
    </valueSet>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Service_Fusion_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Fusion_ID__c</fullName>
    <externalId>true</externalId>
    <label>Service Fusion ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

David 2 Probo medical/force-app/main/default/objects/WorkOrder/fields/Service_Fusion_Techs__c.field-meta.xml
<CustomField>
    <fullName>Service_Fusion_Techs__c</fullName>
    <label>Service Fusion Techs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

David 2 Probo medical/outputs/flow_inventory_2026-08-25/retrieved-source/classes/WorkOrderTriggerHelper.cls
public class WorkOrderTriggerHelper {
    
    public void handler (Boolean isAfter, Boolean isBefore, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isUndelete, List<WorkOrder> newList, List<WorkOrder> oldList, Map<Id,WorkOrder> newMap, Map<Id,WorkOrder> OldMap) {
        if (isBefore) {
            for (WorkOrder wo : newList) {
                List<String> techIds;
                String fieldServiceEngineers = '';
                if (isInsert) {
                    if (wo.Service_Fusion_Techs__c != null) {
                        techIds = wo.Service_Fusion_Techs__c.split(';');
                        List<Field_Service_Engineer__c> techs = [SELECT Id, Name, Service_Fusion_ID__c FROM Field_Service_Engineer__c WHERE Service_Fusion_ID__c in: techIds];
                        for (Field_Service_Engineer__c fse : techs) {
                            fieldServiceEngineers += fse.Name + ';';
                        } 
                        wo.Field_Service_Engineer__c = fieldServiceEngineers;
                    } else if (wo.Field_Service_Engineer__c != null) {
                        techIds = wo.Field_Service_Engineer__c.split(';');
                        List<Field_Service_Engineer__c> techs = [SELECT Id, Name, Service_Fusion_ID__c FROM Field_Service_Engineer__c WHERE Name in: techIds];
                        for (Field_Service_Engineer__c fse : techs) {
                            fieldServiceEngineers += fse.Service_Fusion_ID__c + ';';
                        } 
                        wo.Service_Fusion_Techs__c = fieldServiceEngineers;
                    }
                } else if (isUpdate) {
                    if (wo.Service_Fusion_Techs__c != null && wo.Service_Fusion_Techs__c != oldMap.get(wo.Id).Service_Fusion_Techs__c) {
                        techIds = wo.Service_Fusion_Techs__c.split(';');
                        List<Field_Service_Engineer__c> techs = [SELECT Id, Name, Service_Fusion_ID__c FROM Field_Service_Engineer__c WHERE Service_Fusion_ID__c in: techIds];
                        for (Field_Service_Engineer__c fse : techs) {
                            fieldServiceEngineers += fse.Name + ';';
                        } 
                        wo.Field_Service_Engineer__c = fieldServiceEngineers;
                    } else if (wo.Field_Service_Engineer__c != null && wo.Field_Service_Engineer__c != oldMap.get(wo.Id).Field_Service_Engineer__c) {
                        techIds = wo.Field_Service_Engineer__c.split(';');
                        List<Field_Service_Engineer__c> techs = [SELECT Id, Name, Service_Fusion_ID__c FROM Field_Service_Engineer__c WHERE Name in: techIds];
                        for (Field_Service_Engineer__c fse : techs) {
                            fieldServiceEngineers += fse.Service_Fusion_ID__c + ';';
                        } 
                        wo.Service_Fusion_Techs__c = fieldServiceEngineers;
                    }
                }
            }
        }
    }
    
}