FLY wire David/force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>What is the current status of this account.  Using global picklist set.</description>
    <inlineHelpText>Enter the current status of this account.  Prospect = non client / Active = Contract signed</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Active_Child_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Active_Child_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Active Child Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Child_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Child_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Child Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Child_Counted__c.field-meta.xml
<CustomField>
    <fullName>Child_Counted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Child Counted</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Signed_Child_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Signed_Child_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Signed Child Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active (Product Live)</fullName>
    </customValue>
    <customValue>
        <fullName>Client Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Created (Not Active)</fullName>
        <default>true</default>
        <label>Created (Not Active)</label>
    </customValue>
    <customValue>
        <fullName>Deactivated</fullName>
    </customValue>
    <customValue>
        <fullName>Disqualified</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Merger</fullName>
    </customValue>
    <customValue>
        <fullName>Never Activated</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Test Payment Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Out of Business</fullName>
        <isActive>false</isActive>
        <label>Out of Business</label>
    </customValue>
    <customValue>
        <fullName>No Longer Client</fullName>
        <isActive>false</isActive>
        <label>No Longer Client</label>
    </customValue>
    <description>States of account</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/classes/AccountChildCountBatch.cls
public class AccountChildCountBatch implements Database.Batchable<sobject>,Schedulable {
    public set<Id> accountIds;
    
    public AccountChildCountBatch(set<Id> accIds){
        accountIds = accIds;
    }
    public Database.QueryLocator start(Database.BatchableContext info) { 
        if(!accountIds.isEmpty()){
            return Database.getQueryLocator('SELECT Id,Child_Counted__c,Child_Accounts__c,ParentId from Account WHERE Id in:accountIds');
        }
        
        return Database.getQueryLocator('SELECT Id,Child_Counted__c,Child_Accounts__c,ParentId from Account WHERE Child_Counted__c = FALSE');
        
    }
    
    public void execute(Database.BatchableContext info, List<Account> accounts) { 
        set<Id> tempAccountIds = new set<Id>();
        for(Account acc : accounts){
            tempAccountIds.add(acc.Id);      
        }
        List<Account> accChilds = new List<Account>([SELECT Id,ParentId,Child_Accounts__c,Active_Child_Accounts__c,Signed_Child_Accounts__c,Account_Status__c FROM Account WHERE ParentId IN: tempAccountIds]);
        for(Account ac: accounts){
            integer count =0;
            integer activeCount =0;
            integer signedCount =0;
            
            for(Account acChild: accChilds){
                if(acChild.ParentId == ac.Id){
                    
                    count = (acChild.Child_Accounts__c!=null?((Integer)acChild.Child_Accounts__c) : 0)+1 + count;
                    activeCount = (acChild.Active_Child_Accounts__c!=null?((Integer)acChild.Active_Child_Accounts__c) : 0)+ activeCount;
                    signedCount = (acChild.Signed_Child_Accounts__c!=null?((Integer)acChild.Signed_Child_Accounts__c) : 0)+ signedCount;
                    
                    if(acChild.Account_Status__c == 'Active (Product Live)'){
                        activeCount++;                       
                    }
                    
                    if(acChild.Account_Status__c == 'Client Signed'){
                        signedCount++;                       
                    }
                }             
            }
            ac.Child_Counted__c = true;
            ac.Child_Accounts__c = count;    
            ac.Active_Child_Accounts__c = activeCount;
            ac.Signed_Child_Accounts__c = signedCount;
        }
        update accounts;
    }
    
    public void finish(Database.BatchableContext info) {     
    } 
    
    public void execute(SchedulableContext sc){
        database.executeBatch(new AccountChildCountBatch(accountIds));
        System.abortJob(sc.getTriggerId());
        
    }
}