FLY wire David/force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>What is the current status of this account.  Using global picklist set.</description>
    <inlineHelpText>Enter the current status of this account.  Prospect = non client / Active = Contract signed</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Active_Parent_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Active_Parent_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Active Parent Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Parent_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Parent_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Parent Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Parent_Counted__c.field-meta.xml
<CustomField>
    <fullName>Parent_Counted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parent Counted</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Signed_Parent_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Signed_Parent_Accounts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Signed Parent Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active (Product Live)</fullName>
    </customValue>
    <customValue>
        <fullName>Client Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Created (Not Active)</fullName>
        <default>true</default>
        <label>Created (Not Active)</label>
    </customValue>
    <customValue>
        <fullName>Deactivated</fullName>
    </customValue>
    <customValue>
        <fullName>Disqualified</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Merger</fullName>
    </customValue>
    <customValue>
        <fullName>Never Activated</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Prospecting</fullName>
    </customValue>
    <customValue>
        <fullName>Test Payment Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
        <isActive>false</isActive>
        <label>Prospect</label>
    </customValue>
    <customValue>
        <fullName>Out of Business</fullName>
        <isActive>false</isActive>
        <label>Out of Business</label>
    </customValue>
    <customValue>
        <fullName>No Longer Client</fullName>
        <isActive>false</isActive>
        <label>No Longer Client</label>
    </customValue>
    <description>States of account</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/classes/AccountParentCountBatch.cls
public class AccountParentCountBatch implements Database.Batchable<sobject>,Schedulable {
    public set<Id> accountIds;
    
    public AccountParentCountBatch(set<Id> accIds){
        accountIds = accIds;
    }
    public Database.QueryLocator start(Database.BatchableContext info) { 
        if(!accountIds.isEmpty()){
            return Database.getQueryLocator('SELECT Id,parent.Parent_Accounts__c,Parent_Accounts__c,Signed_Parent_Accounts__c,Parent.Signed_Parent_Accounts__c,Active_Parent_Accounts__c,Parent.Active_Parent_Accounts__c,Parent.Account_Status__c,ParentId from Account WHERE Id in:accountIds');
        }
        return Database.getQueryLocator('SELECT Id,parent.Parent_Accounts__c,Parent_Accounts__c,Signed_Parent_Accounts__c,Parent.Signed_Parent_Accounts__c,Active_Parent_Accounts__c,Parent.Active_Parent_Accounts__c,Parent.Account_Status__c,ParentId from Account WHERE Parent_Counted__c = FALSE');
    }
    
    public void execute(Database.BatchableContext info, List<Account> accounts) { 
        
        for(Account acc : accounts){
            acc.Signed_Parent_Accounts__c = 0;
            acc.Active_Parent_Accounts__c = 0;
            acc.Parent_Accounts__c = 0;
            acc.Parent_Counted__c = true;
            if(acc.ParentId!=NULL){
                acc.Parent_Accounts__c = 1;
                if(acc.parent.Parent_Accounts__c!=NULL){
                    acc.Parent_Accounts__c = acc.parent.Parent_Accounts__c+1;
                }
                
                if(acc.parent.Signed_Parent_Accounts__c!=NULL){
                    acc.Signed_Parent_Accounts__c = acc.parent.Signed_Parent_Accounts__c;
                }
                if(acc.parent.Account_Status__c == 'Client Signed'){
                    acc.Signed_Parent_Accounts__c++;
                }
                
                if(acc.parent.Active_Parent_Accounts__c!=NULL){
                    acc.Active_Parent_Accounts__c = acc.parent.Active_Parent_Accounts__c;
                }
                if(acc.parent.Account_Status__c == 'Active (Product Live)'){
                    acc.Active_Parent_Accounts__c++;
                }
            }            
        }
        update accounts;
    }
    
    public void finish(Database.BatchableContext info) {     
    } 
    
    public void execute(SchedulableContext sc){
        database.executeBatch(new AccountParentCountBatch(accountIds));
        System.abortJob(sc.getTriggerId());
    }
}