FLY wire David/force-app/main/default/objects/Account/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Legal Name of the Account</description>
    <inlineHelpText>Legal Name of the Account</inlineHelpText>
    <label>Client Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Separate_Legal_Entity_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Separate_Legal_Entity_Tax_ID__c</fullName>
    <description>Created from JIRA ticket: BOPI-344.</description>
    <inlineHelpText>Is this Account a separate legal entity or have a different tax id than its parent account?</inlineHelpText>
    <label>Separate Legal Entity/Tax ID?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Tax id number copied from the KYC Application</description>
    <inlineHelpText>This is the Tax Id from the last KYC Application</inlineHelpText>
    <label>Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/recordTypes/Strategic_Partner.recordType-meta.xml
<RecordType>
    <fullName>Strategic_Partner</fullName>
    <active>true</active>
    <description>Companies we are trying to create a partnership with. May or may not include revenue share (Ex. Nelnet, Intrinsiq))</description>
    <label>Strategic Partner</label>
</RecordType>

FLY wire David/force-app/main/default/objects/AccountContactRelation/fields/Billing_Contact_for_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_for_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for SALDEV-1045</description>
    <label>Billing Contact for Account</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Contact_Automation_Bypass_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Contact_Automation_Bypass_DateTime__c</fullName>
    <description>Used for flow automation bypass of validation rules</description>
    <inlineHelpText>Used for flow automation bypass of validation rules</inlineHelpText>
    <label>Automation Bypass DateTime</label>
    <type>DateTime</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box when a sales/RM/Partner contact is no longer active.  They may have changed roles w/in the company or left the company. They no longer interact with Flywire.</description>
    <inlineHelpText>Check this box when a sales/RM/Partner contact is no longer active with Flywire.</inlineHelpText>
    <label>Inactive?</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <description>Created from JIRA ticket: BOPI-240.</description>
    <label>Auto Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.</description>
    <formula>Account.Client_Legal_Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Legal Entity Name</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/SBQQ__RenewalTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalTerm__c</fullName>
    <description>Specify the term of the renewal. By default, it matches the original contract term.</description>
    <inlineHelpText>Enter the expected terms for the renewed contract</inlineHelpText>
    <label>Renewal Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.
This field is twinned from the order which is also twinned from the quote and subsequently updated from the Account via the (ACC) Account Triggered Quote Updater flow</description>
    <label>Tax Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/fields/Opp_Bypass_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Opp_Bypass_DateTime__c</fullName>
    <description>Sysadmin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</description>
    <inlineHelpText>Admin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</inlineHelpText>
    <label>Opp Bypass DateTime</label>
    <type>DateTime</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For HC Partners. When Account (Contract) is with Partner, fill in what HC account this opportunity is for. BOPI-451 Filled in by User, used in Flow to auto fill in Quote Line Ship To Account field.</description>
    <inlineHelpText>Equals the Opp Account, unless the Opp is contracted with a Partner, in which case it&apos;s the serviced Account</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/recordTypes/Strategic_Partner.recordType-meta.xml
<RecordType>
    <fullName>Strategic_Partner</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunity record for Strategic Partner</description>
    <label>Strategic Partner</label>
</RecordType>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <defaultValue>&quot;Yes&quot;</defaultValue>
    <description>Created from JIRA ticket: BOPI-240.</description>
    <label>Auto Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.</description>
    <formula>SBQQ__Account__r.Client_Legal_Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Legal Entity Name</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Owner_Expiration_Notice__c.field-meta.xml
<CustomField>
    <fullName>Owner_Expiration_Notice__c</fullName>
    <defaultValue>(&quot;90&quot;)</defaultValue>
    <description>Created for SALDEV-980.</description>
    <label>Owner Expiration Notice</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
                <label>15 Days</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 Days</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 Days</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <default>true</default>
                <label>90 Days</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>120 Days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Bypass_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Quote_Bypass_DateTime__c</fullName>
    <description>BOPI-581 Sysadmin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</description>
    <inlineHelpText>Admin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</inlineHelpText>
    <label>Quote Bypass DateTime</label>
    <type>DateTime</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BOPI-36 Ship To Account to add subsidiaries to &apos;parent&apos; contracts</description>
    <inlineHelpText>Equals the Opp Account, unless the Opp is contracted with a Partner, in which case it&apos;s the serviced Account</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Ship To Account)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.
This field is updated from the Account via the (ACC) Account Triggered Quote Updater flow</description>
    <label>Tax Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for BOPI-345</description>
    <inlineHelpText>Used to twin the Ship to Account from Quote Line to Subscription</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Ship To Account)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>Alternative for Checkbox when you have to know they answered the question.</description>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/classes/ContractRenewalOppBatchTest.cls
@IsTest
public class ContractRenewalOppBatchTest {

    private static final Id RUNNING_USER_ID = UserInfo.getUserId();

    // --- MOCK IMPLEMENTATION FOR HTTP ---
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setStatus('OK');
            res.setBody('{"status": "success"}');
            return res;
        }
    }

    private static Id getAccountRecordTypeId(String developerName) {
        return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
    }

    // Helper method to generate common setup requirements
    private static Pricebook2 getPricebook() {
        Pricebook2 pb;
        List<Pricebook2> pbs = [SELECT Id FROM Pricebook2 WHERE Name = 'CPQ' LIMIT 1];
        if (pbs.isEmpty()) {
            pb = new Pricebook2(Name = 'CPQ', IsActive = true);
            insert pb;
        } else {
            pb = pbs[0];
        }
        return pb;
    }

    /** ✅ Scenario 1: Valid Contract Renewal (Success Path) **/
    @IsTest
    static void testValidRenewalScenario() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Date contractEndDate = Date.today().addDays(60);
        Date contractStartDate = contractEndDate.addMonths(-12);
        Pricebook2 pb = getPricebook();
        
        Account acc = new Account(
            Name = 'Flywire Renewal Account', 
            Client_Legal_Entity_Name__c = 'Edu Corp', 
            Tax_ID__c = '123456789', 
            Separate_Legal_Entity_Tax_ID__c = 'No', 
            OwnerId = RUNNING_USER_ID,
            BillingStreet = '123 Main St', BillingCity = 'New York', BillingState = 'NY', BillingPostalCode = '10001', BillingCountry = 'United States',
            ShippingStreet = '456 Ship St', ShippingCity = 'New York', ShippingState = 'NY', ShippingPostalCode = '10001', ShippingCountry = 'United States'
        ); 
        insert acc;

        Opportunity opp = new Opportunity(
            AccountId = acc.Id, Name = 'Test Renewal Opp Name', StageName = 'Discovery/Qualifying', 
            CloseDate = Date.today().addMonths(3), Opp_Bypass_DateTime__c = System.now() 
        ); 
        insert opp;

        Contact billingCon = new Contact(
            FirstName = 'John', LastName = 'Doe', Email = 'john.doe@flywire.com', 
            AccountId = acc.Id, Inactive__c = false, Contact_Automation_Bypass_DateTime__c = System.now()
        ); 
        insert billingCon;

        insert new OpportunityContactRole(OpportunityId = opp.Id, ContactId = billingCon.Id, Role = 'Decision Maker', IsPrimary = true);

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Status__c = 'Draft', SBQQ__Account__c = acc.Id, SBQQ__Opportunity2__c = opp.Id, 
            Owner_Expiration_Notice__c = '90', Quote_Bypass_DateTime__c = System.now()
        ); 
        insert testQuote;
        
        testQuote.SBQQ__Status__c = 'Client Approved';
        update testQuote;

        AccountContactRelation existingAcr = [SELECT Id FROM AccountContactRelation WHERE AccountId = :acc.Id AND ContactId = :billingCon.Id LIMIT 1];
        existingAcr.Roles = 'Decision Maker';
        existingAcr.Billing_Contact_For_Account__c = true;
        update existingAcr;

        Contract c = new Contract(
            AccountId = acc.Id, Pricebook2Id = pb.Id, StartDate = contractStartDate, EndDate = contractEndDate,
            Auto_Renewal__c = 'Yes', SBQQ__RenewalForecast__c = false, Status = 'FW_Activated_Draft', 
            OwnerExpirationNotice = '90', SBQQ__RenewalTerm__c = 12, SBQQ__Quote__c = testQuote.Id, OwnerId = RUNNING_USER_ID
        );
        insert c;

        Product2 prod = new Product2(Name = 'Payments', IsActive = true, SBQQ__SubscriptionPricing__c = 'Fixed Price', SBQQ__SubscriptionTerm__c = 12);
        insert prod;

        SBQQ__Subscription__c sub = new SBQQ__Subscription__c(
            SBQQ__Contract__c = c.Id, SBQQ__Account__c = acc.Id, SBQQ__Product__c = prod.Id,
            SBQQ__Quantity__c = 1, SBQQ__SubscriptionStartDate__c = contractStartDate, Ship_To_Account__c = acc.Id 
        );
        insert sub;

        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest(); 

        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(true, updated.SBQQ__RenewalForecast__c, 'Forecast should be TRUE.');
    }

    /** ❌ Scenario 2: Strategic Partner Excluded **/
    @IsTest
    static void testStrategicPartnerExclusion() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Id partnerRtId = getAccountRecordTypeId('Strategic_Partner');
        Pricebook2 pb = getPricebook();
        
        Account acc = new Account(
            Name = 'Flywire Strategic Account', RecordTypeId = partnerRtId, Client_Legal_Entity_Name__c = 'Strategic Corp',
            Tax_ID__c = 'TX123456', Separate_Legal_Entity_Tax_ID__c = 'No', OwnerId = RUNNING_USER_ID,
            BillingStreet = '123 St', BillingCity = 'NY', BillingState = 'NY', BillingPostalCode = '10001', BillingCountry = 'United States',
            ShippingStreet = '123 St', ShippingCity = 'NY', ShippingState = 'NY', ShippingPostalCode = '10001', ShippingCountry = 'United States'
        ); insert acc;

        Opportunity opp = new Opportunity(AccountId = acc.Id, Name = 'Strategic Opp', StageName = 'Discovery/Qualifying', CloseDate = Date.today().addMonths(3), Opp_Bypass_DateTime__c = System.now());
        insert opp;

        Contact billingCon = new Contact(FirstName = 'Strategic', LastName = 'Rep', Email = 'strat@flywire.com', AccountId = acc.Id, Contact_Automation_Bypass_DateTime__c = System.now());
        insert billingCon;

        insert new OpportunityContactRole(OpportunityId = opp.Id, ContactId = billingCon.Id, Role = 'Decision Maker', IsPrimary = true);

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(SBQQ__Status__c = 'Client Approved', SBQQ__Account__c = acc.Id, SBQQ__Opportunity2__c = opp.Id, Quote_Bypass_DateTime__c = System.now());
        insert testQuote;

        // CRITICAL FIX: Added Pricebook2Id and OwnerExpirationNotice
        Contract c = new Contract(
            AccountId = acc.Id, Pricebook2Id = pb.Id, StartDate = Date.today().addMonths(-12), 
            EndDate = Date.today().addDays(60), Auto_Renewal__c = 'Yes', Status = 'FW_Activated_Draft', 
            OwnerExpirationNotice = '90', SBQQ__RenewalTerm__c = 12, SBQQ__Quote__c = testQuote.Id
        );
        insert c;

        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest();

        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(false, updated.SBQQ__RenewalForecast__c, 'Strategic Partner should be excluded.');
    }

    /** ❌ Scenario 3: Missing Required Account Fields & Invalid Tax ID Helper Path **/
    @IsTest
    static void testMissingRequiredAccountFields() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Pricebook2 pb = getPricebook();
        
        // Setup an Account with completely empty details and a generic '00000' Tax ID to hit the isInvalidTaxId block
        Account acc = new Account(
            Name = 'Missing Fields Account',  
            Tax_ID__c = '000-00'
        );
        insert acc;

        Opportunity opp = new Opportunity(AccountId = acc.Id, Name = 'Missing Opp', StageName = 'Discovery/Qualifying', CloseDate = Date.today().addMonths(3), Opp_Bypass_DateTime__c = System.now());
        insert opp;

        Contact billingCon = new Contact(FirstName = 'Test', LastName = 'User', AccountId = acc.Id, Contact_Automation_Bypass_DateTime__c = System.now());
        insert billingCon;

        insert new OpportunityContactRole(OpportunityId = opp.Id, ContactId = billingCon.Id, Role = 'Decision Maker', IsPrimary = true);

        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(SBQQ__Status__c = 'Client Approved', SBQQ__Account__c = acc.Id, SBQQ__Opportunity2__c = opp.Id, Quote_Bypass_DateTime__c = System.now());
        insert testQuote;

        // CRITICAL FIX: Added Pricebook2Id and OwnerExpirationNotice
        Contract c = new Contract(
            AccountId = acc.Id, Pricebook2Id = pb.Id, StartDate = Date.today().addMonths(-12), 
            EndDate = Date.today().addDays(60), Auto_Renewal__c = 'Yes', Status = 'FW_Activated_Draft', 
            OwnerExpirationNotice = '90', SBQQ__RenewalTerm__c = 12, SBQQ__Quote__c = testQuote.Id
        );
        insert c;

        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest();

        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(false, updated.SBQQ__RenewalForecast__c, 'Should remain false due to validation failures');
    }
}