FLY wire David/force-app/main/default/objects/Account/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Legal Name of the Account</description>
    <inlineHelpText>Legal Name of the Account</inlineHelpText>
    <label>Client Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Has_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Has_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is at least 1 related contact with Billing Contact for Account = True on the Account Contact Relationship object.</description>
    <inlineHelpText>RollsUp the value for Billing Contact for Account = True on the Account Contact Relationship object.</inlineHelpText>
    <label>Has Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is the RM for this account?</description>
    <inlineHelpText>Who is the RM for this account?</inlineHelpText>
    <label>Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Separate_Legal_Entity_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Separate_Legal_Entity_Tax_ID__c</fullName>
    <description>Created from JIRA ticket: BOPI-344.</description>
    <inlineHelpText>Is this Account a separate legal entity or have a different tax id than its parent account?</inlineHelpText>
    <label>Separate Legal Entity/Tax ID?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Tax id number copied from the KYC Application</description>
    <inlineHelpText>This is the Tax Id from the last KYC Application</inlineHelpText>
    <label>Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/recordTypes/Strategic_Partner.recordType-meta.xml
<RecordType>
    <fullName>Strategic_Partner</fullName>
    <active>true</active>
    <description>Companies we are trying to create a partnership with. May or may not include revenue share (Ex. Nelnet, Intrinsiq))</description>
    <label>Strategic Partner</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Contact/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to identify this as the official person to send bills to for the associated Client.</description>
    <inlineHelpText>Check to identify this as the official person to send bills to for the associated Client.</inlineHelpText>
    <label>Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Manager__c</fullName>
    <description>Marketo Only field.</description>
    <formula>Account.Relationship_Manager__r.FirstName &amp;&quot; &quot;&amp; Account.Relationship_Manager__r.LastName</formula>
    <inlineHelpText>Marketo Only field.</inlineHelpText>
    <label>Relationship Manager</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <description>Created from JIRA ticket: BOPI-240.</description>
    <label>Auto Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact sent to NetSuite</description>
    <inlineHelpText>Billing Contact sent to NetSuite</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.</description>
    <formula>Account.Client_Legal_Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Legal Entity Name</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Is_Schedule_Flow_Checked__c.field-meta.xml
<CustomField>
    <fullName>Is_Schedule_Flow_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is set when the schedule flow is run for Renewal Opportunity.</description>
    <inlineHelpText>This field is set when the schedule flow is run for Renewal Opportunity.</inlineHelpText>
    <label>Is Schedule Flow Checked</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.
This field is twinned from the order which is also twinned from the quote and subsequently updated from the Account via the (ACC) Account Triggered Quote Updater flow</description>
    <label>Tax Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>Alternative for Checkbox when you have to know they answered the question.</description>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/classes/ContractRenewalOppBatch.cls
public class ContractRenewalOppBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date contractEndDate180Days = Date.today().addDays(180);
        Date contractEndDate60Days  = Date.today().addDays(60);

        Set<String> renewalStatuses = new Set<String>{'FW_Activated_Draft', 'FW Activated', 'Activated'};
        Set<String> excludedStatuses = new Set<String>{'Terminated', 'Superseded', 'Terminated_Draft', 'Superseded_Draft', 'Expired_Draft', 'Expired'};

        // Query all required Account fields in the start method to avoid SOQL inside the loop
        return Database.getQueryLocator([
            SELECT Id, Auto_Renewal__c, SBQQ__RenewalForecast__c, EndDate, ContractNumber,
               AccountId, Billing_Contact__c, Pricebook2Id,
               Account.Name, 
               Account.Has_Billing_Contact__c,
               Account.Client_Legal_Entity_Name__c, 
               Account.Tax_ID__c, 
               Account.Separate_Legal_Entity_Tax_ID__c,
               Account.BillingStreet, Account.BillingCity, 
               Account.BillingState, Account.BillingPostalCode, Account.BillingCountry,
               Account.ShippingStreet, Account.ShippingCity, 
               Account.ShippingState, Account.ShippingPostalCode, Account.ShippingCountry,
               Account.Relationship_Manager__r.Email, Account.Owner.Email
            FROM Contract
            WHERE SBQQ__RenewalForecast__c = false
              AND Account.RecordType.DeveloperName != 'Strategic_Partner'
              AND Pricebook2.Name = 'CPQ'
              AND Status IN :renewalStatuses
              AND Status NOT IN :excludedStatuses
              AND (
                      (Auto_Renewal__c = 'No'  AND EndDate <= :contractEndDate180Days)
                   OR (Auto_Renewal__c = 'Yes' AND EndDate <= :contractEndDate60Days)
              )
        ]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Contract> contractsToUpdate = new List<Contract>();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        // Environment configuration calculated once per batch scope
        Boolean isSandbox = false;
        String baseUrl = 'https://login.salesforce.com';
        if (Test.isRunningTest()) {
            baseUrl = 'https://test.salesforce.com';
        } else {
            try {
                baseUrl = URL.getOrgDomainUrl().toExternalForm();
                isSandbox = baseUrl.contains('sandbox');
            } catch (Exception e) {}
        }
        String subjectPrefix = (Test.isRunningTest() || isSandbox ? 'No Action Required – ' : 'Action Required – ');

        for (Contract c : (List<Contract>) scope) {
            List<String> missingFields = new List<String>();
            Boolean hasValidBillingContact = (c.Account.Has_Billing_Contact__c == true);
            
            if (!hasValidBillingContact) missingFields.add('Billing Contact');
            if (String.isBlank(c.Account.Client_Legal_Entity_Name__c)) missingFields.add('Client Legal Entity Name');
            if (isInvalidTaxId(c.Account.Tax_ID__c)) missingFields.add('Tax ID');
            
            String sepPick = c.Account.Separate_Legal_Entity_Tax_ID__c;
            if (String.isBlank(sepPick) || sepPick == 'None') missingFields.add('Separate Legal Entity/Tax ID');

            if (String.isBlank(c.Account.BillingStreet) || String.isBlank(c.Account.BillingCity) || 
                String.isBlank(c.Account.BillingState) || String.isBlank(c.Account.BillingPostalCode) || 
                String.isBlank(c.Account.BillingCountry)) missingFields.add('Billing Address');

            if (String.isBlank(c.Account.ShippingStreet) || String.isBlank(c.Account.ShippingCity) || 
                String.isBlank(c.Account.ShippingState) || String.isBlank(c.Account.ShippingPostalCode) || 
                String.isBlank(c.Account.ShippingCountry)) missingFields.add('Shipping Address');

            // Build logic for emails if data is missing
            if (!missingFields.isEmpty()) {
                String missingFieldsHtml = '<ul>';
                for (String fieldName : missingFields) missingFieldsHtml += '<li>' + fieldName + '</li>';
                missingFieldsHtml += '</ul>';

                String emailBodyHtml = '<p>The following fields are missing for account ' +
                    '<a href="' + baseUrl + '/' + c.AccountId + '">' + c.Account.Name + '</a>. Please update them before ' +
                    String.valueOf(c.EndDate) + ' to prevent renewal issues.</p>' + missingFieldsHtml;

                if (!hasValidBillingContact) {
                    emailBodyHtml += '<p>Contract <a href="' + baseUrl + '/' + c.Id + '">' + c.ContractNumber + 
                    '</a> does not have a Billing Contact for an Account Set. ' +
                    'Either mark an existing Account contact for Billing contact for account to true or create a new Account contact with Billing Contact for Account = True on the account ' + 
                    '<a href="' + baseUrl + '/' + c.AccountId + '">' + c.Account.Name + '</a>.</p>';
                }

                Set<String> recipients = new Set<String>();
                if (c.Account.Relationship_Manager__r != null && !String.isBlank(c.Account.Relationship_Manager__r.Email)) recipients.add(c.Account.Relationship_Manager__r.Email);
                if (!String.isBlank(c.Account.Owner.Email)) recipients.add(c.Account.Owner.Email);

                for (String emailAddr : recipients) {
                    Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
                    msg.setToAddresses(new String[]{emailAddr});
                    msg.setSubject(subjectPrefix + 'Missing Field Data for Contract Renewal: ' + c.ContractNumber);
                    msg.setHtmlBody(emailBodyHtml);
                    emails.add(msg);
                }
            }

            c.SBQQ__RenewalForecast__c = (missingFields.isEmpty() && hasValidBillingContact);
            c.Is_Schedule_Flow_Checked__c = c.SBQQ__RenewalForecast__c;
            contractsToUpdate.add(c);
        }

        if (!contractsToUpdate.isEmpty()) update contractsToUpdate;
        if (!emails.isEmpty() && !Test.isRunningTest()) Messaging.sendEmail(emails);
    }

    public void finish(Database.BatchableContext bc) {}

    private static Boolean isInvalidTaxId(String taxId) {
        if (String.isBlank(taxId)) return true;
        String digitsOnly = taxId.replaceAll('[^0-9]', '');
        return (!String.isBlank(digitsOnly) && digitsOnly.replaceAll('0','').length() == 0);
    }
}