FLY wire David/force-app/main/default/objects/Account/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Legal Name of the Account</description>
    <inlineHelpText>Legal Name of the Account</inlineHelpText>
    <label>Client Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Has_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Has_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether there is at least 1 related contact with Billing Contact for Account = True on the Account Contact Relationship object.</description>
    <inlineHelpText>RollsUp the value for Billing Contact for Account = True on the Account Contact Relationship object.</inlineHelpText>
    <label>Has Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is the RM for this account?</description>
    <inlineHelpText>Who is the RM for this account?</inlineHelpText>
    <label>Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Separate_Legal_Entity_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Separate_Legal_Entity_Tax_ID__c</fullName>
    <description>Created from JIRA ticket: BOPI-344.</description>
    <inlineHelpText>Is this Account a separate legal entity or have a different tax id than its parent account?</inlineHelpText>
    <label>Separate Legal Entity/Tax ID?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>YesNo</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Tax id number copied from the KYC Application</description>
    <inlineHelpText>This is the Tax Id from the last KYC Application</inlineHelpText>
    <label>Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <description>Account Record type for B2B Segment</description>
    <label>B2B</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Account/recordTypes/Education.recordType-meta.xml
<RecordType>
    <fullName>Education</fullName>
    <active>true</active>
    <description>Record Type for Current and Potential Education Clients.</description>
    <label>Education</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Account/recordTypes/Strategic_Partner.recordType-meta.xml
<RecordType>
    <fullName>Strategic_Partner</fullName>
    <active>true</active>
    <description>Companies we are trying to create a partnership with. May or may not include revenue share (Ex. Nelnet, Intrinsiq))</description>
    <label>Strategic Partner</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Account/recordTypes/Travel.recordType-meta.xml
<RecordType>
    <fullName>Travel</fullName>
    <active>true</active>
    <description>Account Record type for the Travel Segment</description>
    <label>Travel</label>
</RecordType>

FLY wire David/force-app/main/default/objects/AccountContactRelation/fields/Billing_Contact_for_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_for_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created for SALDEV-1045</description>
    <label>Billing Contact for Account</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to identify this as the official person to send bills to for the associated Client.</description>
    <inlineHelpText>Check to identify this as the official person to send bills to for the associated Client.</inlineHelpText>
    <label>Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Contact_Automation_Bypass_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Contact_Automation_Bypass_DateTime__c</fullName>
    <description>Used for flow automation bypass of validation rules</description>
    <inlineHelpText>Used for flow automation bypass of validation rules</inlineHelpText>
    <label>Automation Bypass DateTime</label>
    <type>DateTime</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box when a sales/RM/Partner contact is no longer active.  They may have changed roles w/in the company or left the company. They no longer interact with Flywire.</description>
    <inlineHelpText>Check this box when a sales/RM/Partner contact is no longer active with Flywire.</inlineHelpText>
    <label>Inactive?</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contact/fields/Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Manager__c</fullName>
    <description>Marketo Only field.</description>
    <formula>Account.Relationship_Manager__r.FirstName &amp;&quot; &quot;&amp; Account.Relationship_Manager__r.LastName</formula>
    <inlineHelpText>Marketo Only field.</inlineHelpText>
    <label>Relationship Manager</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <description>Created from JIRA ticket: BOPI-240.</description>
    <label>Auto Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing Contact sent to NetSuite</description>
    <inlineHelpText>Billing Contact sent to NetSuite</inlineHelpText>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.</description>
    <formula>Account.Client_Legal_Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Legal Entity Name</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/SBQQ__RenewalTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalTerm__c</fullName>
    <description>Specify the term of the renewal. By default, it matches the original contract term.</description>
    <inlineHelpText>Enter the expected terms for the renewed contract</inlineHelpText>
    <label>Renewal Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Contract/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.
This field is twinned from the order which is also twinned from the quote and subsequently updated from the Account via the (ACC) Account Triggered Quote Updater flow</description>
    <label>Tax Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/fields/No_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>No_Approvals_Required__c</fullName>
    <description>BOPI-844 This quote field allows the quote to by pass all approval rules</description>
    <formula>SBQQ__PrimaryQuote__r.No_Approvals_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Approvals Required</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/fields/Opp_Bypass_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Opp_Bypass_DateTime__c</fullName>
    <description>Sysadmin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</description>
    <inlineHelpText>Admin purpose only. Not for reporting. Set by Flows to bypass validation rules. Works with Opp bypass checkbox formula field.</inlineHelpText>
    <label>Opp Bypass DateTime</label>
    <type>DateTime</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Opportunity/recordTypes/B2B.recordType-meta.xml
<RecordType>
    <fullName>B2B</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Record type for the B2B vertical</description>
    <label>B2B</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Opportunity/recordTypes/Education.recordType-meta.xml
<RecordType>
    <fullName>Education</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Record Type for Current and Potential Education Clients.</description>
    <label>Education</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Opportunity/recordTypes/Strategic_Partner.recordType-meta.xml
<RecordType>
    <fullName>Strategic_Partner</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Opportunity record for Strategic Partner</description>
    <label>Strategic Partner</label>
</RecordType>

FLY wire David/force-app/main/default/objects/Opportunity/recordTypes/Travel.recordType-meta.xml
<RecordType>
    <fullName>Travel</fullName>
    <active>true</active>
    <businessProcess>Sales Process</businessProcess>
    <description>Travel vertical Opportunity record</description>
    <label>Travel</label>
</RecordType>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <defaultValue>&quot;Yes&quot;</defaultValue>
    <description>Created from JIRA ticket: BOPI-240.</description>
    <label>Auto Renewal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created from JIRA ticket: BOPI-32.</description>
    <inlineHelpText>Select a Billing Contact related to the Account Hierarchy</inlineHelpText>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3 AND 4</booleanFilter>
        <errorMessage>Contact must be active and marked as the Billing contact on their Contact record.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Billing_Contact__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Select the Billing Contact for this Client. Contact must be active and marked as the Billing contact on their Contact record.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Billing Contact)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Client_Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Legal_Entity_Name__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.</description>
    <formula>SBQQ__Account__r.Client_Legal_Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Legal Entity Name</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/No_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>No_Approvals_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BOPI-844 Checking this field allows the quote to by pass all approval rules</description>
    <inlineHelpText>Checking this field allows the quote to by pass all approval rules</inlineHelpText>
    <label>No Approvals Required</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Owner_Expiration_Notice__c.field-meta.xml
<CustomField>
    <fullName>Owner_Expiration_Notice__c</fullName>
    <defaultValue>(&quot;90&quot;)</defaultValue>
    <description>Created for SALDEV-980.</description>
    <label>Owner Expiration Notice</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
                <label>15 Days</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>30 Days</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>45 Days</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>60 Days</label>
            </value>
            <value>
                <fullName>90</fullName>
                <default>true</default>
                <label>90 Days</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>120 Days</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-227.
This field is updated from the Account via the (ACC) Account Triggered Quote Updater flow</description>
    <label>Tax Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/YesNo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <description>Alternative for Checkbox when you have to know they answered the question.</description>
    <masterLabel>YesNo</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/classes/ContractRenewalOpportunityBatchTest.cls
/**
 * Test class for ContractRenewalOppBatch.
 * Validates renewal forecasting logic by verifying Account fields and 
 * AccountContactRelation (ACR) based Billing Contact requirements.
 * * Note: Slack notifications are bypassed via naming conventions ("Flywire" in Account Name, 
 * "Test" in Opportunity Name) as per the Record-Triggered Flow configuration.
 */
@IsTest
public class ContractRenewalOpportunityBatchTest {

    private static final Id RUNNING_USER_ID = UserInfo.getUserId();

    // --- MOCK IMPLEMENTATION (Required for all HTTP callouts) ---
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setStatus('OK');
            res.setBody('{"status": "success", "message": "Mock callout complete."}');
            return res;
        }
    }

    // --- Helper Methods ---

    /**
     * Safely retrieves a Record Type Id by Developer Name.
     * Uses your specific record types: Education, B2B, Travel, Strategic_Partner.
     */
    private static Id getAccountRecordTypeId(String developerName) {
        Id recordTypeId;
        try {
            recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
        } catch (Exception e) {
            // Fallback to name if developer name check fails
            for(Schema.RecordTypeInfo rt : Account.SObjectType.getDescribe().getRecordTypeInfos()) {
                if(rt.getName() == developerName) return rt.getRecordTypeId();
            }
            recordTypeId = Schema.SObjectType.Account.getRecordTypeInfos()[0].getRecordTypeId();
        }
        return recordTypeId;
    }

    /**
     * Helper to create a valid ACR for an Account and ensure the rollup flag is set.
     */
    private static void createValidACR(Account acc) {
        Contact con = new Contact(
            FirstName = 'John', 
            LastName = 'Billing', 
            Email = 'john.billing@flywire.com', 
            AccountId = acc.Id, 
            Inactive__c = false,
            Billing_Contact__c = true, // Satisfies potential rollup dependencies
            // 🛑 BYPASS logic for Contact automation
            Contact_Automation_Bypass_DateTime__c = System.now().addHours(-1)
        ); 
        insert con;

        // Fetch the ACR created automatically by the Contact insert
        AccountContactRelation acr = [
            SELECT Id, Billing_Contact_For_Account__c, Roles 
            FROM AccountContactRelation 
            WHERE AccountId = :acc.Id AND ContactId = :con.Id 
            LIMIT 1
        ];

        acr.Billing_Contact_For_Account__c = true;
        acr.Roles = 'Decision Maker;Business User'; // Satisfies VALID_ROLES check in Batch
        update acr;

        // Manually update the flag on Account as required by Batch Logic
        // Handled in try-catch in case it is a system-calculated Rollup Summary
        try {
            acc.Has_Billing_Contact__c = true;
            update acc;
        } catch (Exception e) {
            System.debug('Account Has_Billing_Contact__c update handled: ' + e.getMessage());
        }
    }

    // --- TEST METHODS ---
    
    /** ✅ Scenario 1: Valid Contract Renewal (Success Path) **/
    @IsTest
    static void testValidRenewalScenario() {
        // --- 1. SET MOCKS ---
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Date contractEndDate = Date.today().addDays(30);
        Date contractStartDate = contractEndDate.addMonths(-12);
        
        // --- 2. SETUP DATA ---
        // Record Type MUST be assigned and NOT Strategic_Partner for SOQL pickup
        Id eduRtId = getAccountRecordTypeId('Education');

        // Name contains 'Flywire' to satisfy flow bypass
        Account acc = new Account(
            Name = 'Flywire Renewal Account', 
            RecordTypeId = eduRtId,
            Client_Legal_Entity_Name__c = 'Edu Corp', 
            Tax_ID__c = 'TX123456', 
            Separate_Legal_Entity_Tax_ID__c = 'No', 
            OwnerId = RUNNING_USER_ID,
            Relationship_Manager__c = RUNNING_USER_ID, 
            BillingStreet = '123 Main St', BillingCity = 'New York', BillingState = 'NY', BillingPostalCode = '10001', BillingCountry = 'United States',
            ShippingStreet = '456 Ship St', ShippingCity = 'New York', ShippingState = 'NY', ShippingPostalCode = '10001', ShippingCountry = 'United States'
        ); 
        insert acc;

        createValidACR(acc);

        Pricebook2 pb = new Pricebook2(Name = 'CPQ', IsActive = true); 
        insert pb;
        
        // Opportunity: Name contains 'Test' to satisfy flow bypass
        Opportunity opp = new Opportunity(
            AccountId = acc.Id, 
            Name = 'Test Renewal Opp Name', 
            StageName = 'Discovery/Qualifying', 
            CloseDate = Date.today().addMonths(3), 
            Opp_Bypass_DateTime__c = System.now().addHours(-1) 
        );
        insert opp;
        
        // Quote Setup: Sequential status transition logic applied
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Status__c = 'Draft', 
            SBQQ__Account__c = acc.Id, 
            SBQQ__Opportunity2__c = opp.Id,
            SBQQ__Primary__c = true, 
            Owner_Expiration_Notice__c = '90', // Required by Batch
            No_Approvals_Required__c = true
        ); 
        insert testQuote;

        // Transitions: Draft -> FW Approved -> Client_Approved (API Name)
        testQuote.SBQQ__Status__c = 'FW Approved';
        update testQuote;

        testQuote.SBQQ__Status__c = 'Client_Approved';
        update testQuote;

        Contract c = new Contract(
            AccountId = acc.Id, 
            Pricebook2Id = pb.Id, 
            StartDate = contractStartDate, 
            EndDate = contractEndDate,
            ContractTerm = 12,
            Auto_Renewal__c = 'Yes', 
            SBQQ__RenewalForecast__c = false, 
            Status = 'FW_Activated_Draft', 
            SBQQ__RenewalTerm__c = 12, 
            SBQQ__Quote__c = testQuote.Id, 
            OwnerId = RUNNING_USER_ID
        );
        insert c;

        // --- 3. EXECUTION ---
        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest(); 

        // --- 4. ASSERTIONS ---
        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(true, updated.SBQQ__RenewalForecast__c, 'Renewal Forecast should be TRUE when valid ACR and Account fields exist.');
    }
    
    /** ❌ Scenario 2: Strategic Partner Excluded **/
    @IsTest
    static void testStrategicPartnerExclusion() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Id partnerRtId = getAccountRecordTypeId('Strategic_Partner');
        Account acc = new Account(
            Name = 'Flywire Strategic Account', 
            RecordTypeId = partnerRtId, 
            Client_Legal_Entity_Name__c = 'Strategic Corp',
            Tax_ID__c = 'TX123456', Separate_Legal_Entity_Tax_ID__c = 'No', OwnerId = RUNNING_USER_ID,
            BillingStreet = '123 Main St', BillingCity = 'New York', BillingState = 'NY', BillingPostalCode = '10001', BillingCountry = 'United States',
            ShippingStreet = '456 Ship St', ShippingCity = 'New York', ShippingState = 'NY', ShippingPostalCode = '10001', ShippingCountry = 'United States'
        ); 
        insert acc;
        
        createValidACR(acc);
        Pricebook2 pb = new Pricebook2(Name = 'CPQ', IsActive = true); insert pb;
        
        Contract c = new Contract(
            AccountId = acc.Id, Pricebook2Id = pb.Id, StartDate = Date.today().addMonths(-12), 
            EndDate = Date.today().addDays(30), Auto_Renewal__c = 'Yes', 
            SBQQ__RenewalForecast__c = false, Status = 'FW_Activated_Draft'
        );
        insert c;

        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest();

        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(false, updated.SBQQ__RenewalForecast__c, 'Strategic Partner contracts must be skipped by the locator.');
    }

    /** ❌ Scenario 3: Missing Required Account Fields **/
    @IsTest
    static void testMissingRequiredAccountFields() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Id eduRtId = getAccountRecordTypeId('Education');
        Account acc = new Account(
            Name = 'Flywire Missing Fields Account', 
            RecordTypeId = eduRtId,
            Client_Legal_Entity_Name__c = null, Tax_ID__c = null, Separate_Legal_Entity_Tax_ID__c = 'No',
            BillingStreet = '123 Main St', BillingCity = 'New York', BillingState = 'NY', BillingPostalCode = '10001', BillingCountry = 'United States',
            ShippingStreet = '456 Ship St', ShippingCity = 'New York', ShippingState = 'NY', ShippingPostalCode = '10001', ShippingCountry = 'United States'
        ); 
        insert acc;
        
        createValidACR(acc);
        Pricebook2 pb = new Pricebook2(Name = 'CPQ', IsActive = true); insert pb;

        Contract c = new Contract(
            AccountId = acc.Id, Pricebook2Id = pb.Id, StartDate = Date.today().addMonths(-12), 
            EndDate = Date.today().addDays(30), Auto_Renewal__c = 'Yes', 
            SBQQ__RenewalForecast__c = false, Status = 'FW_Activated_Draft'
        );
        insert c;

        Test.startTest();
            Database.executeBatch(new ContractRenewalOppBatch(), 1);
        Test.stopTest();

        Contract updated = [SELECT SBQQ__RenewalForecast__c FROM Contract WHERE Id = :c.Id];
        System.assertEquals(false, updated.SBQQ__RenewalForecast__c, 'Forecast should be FALSE if Account fields are missing.');
    }
}