FLY wire David/force-app/main/default/objects/Account/fields/KYC_Status__c.field-meta.xml
<CustomField>
    <fullName>KYC_Status__c</fullName>
    <description>KYC Status, to be filled in automatically by integration with PassFort</description>
    <inlineHelpText>Applications are created as &apos;Applied&apos;, they can then be &apos;Approved&apos; or &apos;Rejected&apos;. If Application status shows &apos;In Review&apos; it should still be considered &apos;Approved&apos;</inlineHelpText>
    <label>KYC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
                <isActive>false</isActive>
                <label>In Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Passfort_KYC_Form__c.field-meta.xml
<CustomField>
    <fullName>Passfort_KYC_Form__c</fullName>
    <label>Passfort KYC Form URL</label>
    <type>Url</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Account/fields/Passfort_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Passfort_Profile_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Passfort Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FLY wire David/force-app/main/default/classes/PassfortFormExpiryAsyncProcessor.cls
public with sharing class PassfortFormExpiryAsyncProcessor implements Database.Batchable<SObject>, Database.AllowsCallouts {

    // When a new application form is created the KYC application can be created or not 
    // depending on the questions answered by the client.
    // 1. If the application is created, the account KYC status will be Applied
    // 2. If the application is not created on the account, the KYC status will be null.
    public final String query = 
        'SELECT Id, Passfort_Profile_Id__c, KYC_Status__c ' +
        'FROM Account ' + 
        'WHERE Passfort_KYC_Form__c != null AND KYC_Status__c IN (\'Applied\',null)';

    public PassfortFormExpiryAsyncProcessor() {}

    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('batch start');
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug('Batch execute - scope size: ' + scope.size());
        Map<String,Boolean> areExpired = PassfortApplicationFormExpiryChecker.areExpired((List<Account>)scope);

        List<Account> scopeAccounts = (List<Account>)scope;
        List<Account> accountsWithExpiredForms = new List<Account>();

        for (Account currentAccount : scopeAccounts) {
            if (areExpired.get(currentAccount.Id)) {
                currentAccount.Passfort_KYC_Form__c = null;
                accountsWithExpiredForms.add(currentAccount);
            }
        }

        update accountsWithExpiredForms;
    }

    public void finish(Database.BatchableContext bc) {}
}