FLY wire David/force-app/main/default/objects/Account/fields/Passfort_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Passfort_Profile_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Passfort Profile Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FLY wire David/force-app/main/default/objects/KYC_Application__c/KYC_Application__c.object-meta.xml
<CustomObject>
    <label>KYC Application</label>
    <nameField>
        <displayFormat>KYC-{00000}</displayFormat>
        <label>KYC Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KYC Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/objects/KYC_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KYC Applications</relationshipLabel>
    <relationshipName>KYC_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

FLY wire David/force-app/main/default/objects/KYC_Application__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Passfort Identifier for KYC application</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Passfort Identifier for KYC application</inlineHelpText>
    <label>Application ID</label>
    <length>205</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FLY wire David/force-app/main/default/objects/KYC_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Application status from Passfort.</description>
    <inlineHelpText>Application applied (submitted but not reviewed for KYC), In Review (KYC in process of reviewing), Approved, Rejected (account declined prior to accepting application), Cancelled (Account Services discontinued after application was initally reviewed)</inlineHelpText>
    <label>Application Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/Passfort_Webhook_Log__c.object-meta.xml
<CustomObject>
    <label>Passfort Webhook Log</label>
    <nameField>
        <displayFormat>PWL-{0000000}</displayFormat>
        <label>Passfort Webhook Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passfort Webhook Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Extracted_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Extracted_Profile_Id__c</fullName>
    <inlineHelpText>Passfort ProfileId extracted from the request body JSON</inlineHelpText>
    <label>Extracted Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Request_body__c.field-meta.xml
<CustomField>
    <fullName>Request_body__c</fullName>
    <description>Request body from webhook.</description>
    <inlineHelpText>Request body from webhook</inlineHelpText>
    <label>Request body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Passfort_Webhook_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the webhook.</description>
    <inlineHelpText>Request body from webhook</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/classes/PassfortProfileAsyncProcessorTest.cls
@isTest
public with sharing class PassfortProfileAsyncProcessorTest {
    @TestSetup
    static void makeData() {
        insert (new Account(Name = 'Test Acct'));
    }

    @isTest
    static void shouldPerformDMLOperations() {
        List<Passfort_Webhook_Log__c> logBeforeProcessing = [SELECT Id FROM Passfort_Webhook_Log__c];
        List<Account> accountBeforeProcessing = [SELECT Id, Name FROM Account];
        List<KYC_Application__c> kycAppsBeforeProcessing = [SELECT Id FROM KYC_Application__c];
        
        Assert.isTrue(logBeforeProcessing.isEmpty());
        Assert.isTrue(!accountBeforeProcessing.isEmpty());
        Assert.isTrue(kycAppsBeforeProcessing.isEmpty());

        accountBeforeProcessing[0].Passfort_Profile_Id__c = 'test_profile_id';

        List<Passfort_Webhook_Log__c> logs = new List<Passfort_Webhook_Log__c>();
        Passfort_Webhook_Log__c log = new Passfort_Webhook_Log__c(
            Status__c = 'Success'
        );
        logs.add(log);

        List<KYC_Application__c> kycApps = new List<KYC_Application__c>();
        KYC_Application__c app = new KYC_Application__c(
            Account__c = accountBeforeProcessing[0].Id,
            Application_ID__c = 'test_app_id'
        );
        kycApps.add(app);

        Test.startTest();
        System.enqueueJob(new PassfortProfileAsyncProcessor(logs, new Set<Account>(accountBeforeProcessing), kycApps));
        Test.stopTest();
        
        List<Passfort_Webhook_Log__c> logAfterProcessing = [SELECT Id, Status__c, Request_Body__c, Extracted_Profile_Id__c FROM Passfort_Webhook_Log__c];
        List<Account> accountsAfterProcessing = [SELECT Id, Passfort_Profile_Id__c FROM Account];
        List<KYC_Application__c> kycAppsAfterProcessing = [SELECT Id, Status__c, Account__c FROM KYC_Application__c];
        
        Assert.isFalse(logAfterProcessing.isEmpty());
        Assert.areEqual('Success', logAfterProcessing[0].Status__c);
        Assert.areEqual('test_profile_id', accountsAfterProcessing[0].Passfort_Profile_Id__c);
        Assert.isFalse(kycAppsAfterProcessing.isEmpty());
        Assert.areEqual(accountsAfterProcessing[0].Id, kycAppsAfterProcessing[0].Account__c);
    }
}