FLY wire David/force-app/main/default/objects/Order/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BOPI-36 Ship To Account to add subsidiaries to &apos;parent&apos; contracts</description>
    <inlineHelpText>Subsidiary Account</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Quote_Line_Rollup_Field_Mapping__mdt/Quote_Line_Rollup_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>SALDEV-1418
custom metadata is created to store field and average field mapping from Quote Line object.
New record can be added here to calculate average of field.</description>
    <label>Quote Line Rollup Fields Mapping</label>
    <pluralLabel>Quote Line Rollup Fields Mappings</pluralLabel>
</CustomObject>

FLY wire David/force-app/main/default/objects/Quote_Line_Rollup_Field_Mapping__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>API name of field</description>
    <inlineHelpText>API name of field</inlineHelpText>
    <label>Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Quote_Line_Rollup_Field_Mapping__mdt/fields/Rollup_Field__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Field__c</fullName>
    <description>API name of average field</description>
    <inlineHelpText>API name of average field</inlineHelpText>
    <label>Rollup Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/Quote_Line_Rollup_Field_Mapping__mdt/fields/Type_of_Operation__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Operation__c</fullName>
    <label>Type of Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Average</fullName>
                <default>true</default>
                <label>Average</label>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Quote__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BOPI-36 Ship To Account to add subsidiaries to &apos;parent&apos; contracts</description>
    <inlineHelpText>Equals the Opp Account, unless the Opp is contracted with a Partner, in which case it&apos;s the serviced Account</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Ship To Account)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Attribute_Code__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Code__c</fullName>
    <description>Stamped from Usage Rates - Attributes lookup object via price rule. This code identifies the unique combination of attributes that drive the usage rate pricing and is sent to analytics and NetSuite</description>
    <inlineHelpText>Attribute code for the combination of Quote Line variables</inlineHelpText>
    <label>Attribute Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Default_Rate_Details__c.field-meta.xml
<CustomField>
    <fullName>Default_Rate_Details__c</fullName>
    <description>Created for ticket BOPI-913</description>
    <label>Default Rate Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Created from JIRA ticket: BOPI-7.</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Payment_Method</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Price_Change__c.field-meta.xml
<CustomField>
    <fullName>Price_Change__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Product is part of price change</description>
    <inlineHelpText>Product is part of price change</inlineHelpText>
    <label>Price Change</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Quote_Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Type__c</fullName>
    <description>Created from JIRA ticket: BOPI-103.</description>
    <formula>IF(NOT(ISBLANK(SBQQ__RenewedSubscription__c)) &amp;&amp; SBQQ__Quantity__c != 0,
    IF( Price_Change__c ,&quot;Price Change&quot;,&quot;Renewal&quot;),
    IF(ISBLANK(SBQQ__UpgradedSubscription__c) &amp;&amp; ISBLANK(SBQQ__RenewedSubscription__c),
        IF( Price_Change__c ,&quot;Price Change&quot;,&quot;New&quot;),
        IF(SBQQ__Quantity__c = 0,
            IF( Price_Change__c ,&quot;Cancellation Price Change&quot;,&quot;Cancellation&quot;),
            IF(SBQQ__Quantity__c &gt; SBQQ__UpgradedSubscription__r.SBQQ__Quantity__c,
                &quot;Quantity Increase&quot;,
                IF(SBQQ__Quantity__c &lt; SBQQ__UpgradedSubscription__r.SBQQ__Quantity__c,
                    &quot;Quantity Reduction&quot;,
                    &quot;Amendment&quot;
                )
            )
        )        
    )
)</formula>
    <label>Quote Line Type</label>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Quote_Line_Type_background__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Type_background__c</fullName>
    <description>Created for BOPI-770. Used for a flow to take the value from the Quote Line Type formula field so that it can be used in a rollup summary field.</description>
    <label>Quote Line Type background</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Rate_Details__c.field-meta.xml
<CustomField>
    <fullName>Rate_Details__c</fullName>
    <description>Created for BOPI-913</description>
    <label>Rate Details</label>
    <length>37689</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Rate_Details_Changed__c.field-meta.xml
<CustomField>
    <fullName>Rate_Details_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BOPI-1048--Refactored the flow.</description>
    <label>Rate Details Changed</label>
    <type>Checkbox</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Account to create related list of Quote Lines added to Parent Account&apos;s contract</description>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Contract Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Transaction_Currency__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Currency__c</fullName>
    <description>Created from JIRA ticket: BOPI-358. Updated label per BOPI-825</description>
    <label>Transaction (Portal) Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Currencies</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Attribute_Code__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Code__c</fullName>
    <description>Stamped from Usage Rates - Attributes lookup object via price rule. This code identifies the unique combination of attributes that drive the usage rate pricing and is sent to analytics and NetSuite</description>
    <inlineHelpText>Attribute code for the combination of Quote Line variables</inlineHelpText>
    <label>Attribute Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Opportunity_Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Id__c</fullName>
    <description>Created from JIRA ticket: BOPI-179.</description>
    <label>Opportunity Line Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Created for BOPI-345</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Method</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Rate_Details__c.field-meta.xml
<CustomField>
    <fullName>Rate_Details__c</fullName>
    <description>Created for SALDEV-913</description>
    <label>Rate Details</label>
    <length>37689</length>
    <type>LongTextArea</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for BOPI-345</description>
    <inlineHelpText>Used to twin the Ship to Account from Quote Line to Subscription</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Ship To Account)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

FLY wire David/force-app/main/default/objects/SBQQ__Subscription__c/fields/Transaction_Currency__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Currency__c</fullName>
    <description>Used to twin value from Currency field on Quote Line to Subscription</description>
    <inlineHelpText>Used to twin value from Currency field on Quote Line to Subscription</inlineHelpText>
    <label>Transaction Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Currencies</valueSetName>
    </valueSet>
</CustomField>

FLY wire David/force-app/main/default/globalValueSets/Payment_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACH</fullName>
    </customValue>
    <customValue>
        <fullName>Alipay</fullName>
    </customValue>
    <customValue>
        <fullName>Amex</fullName>
    </customValue>
    <customValue>
        <fullName>Amex Gateway</fullName>
    </customValue>
    <customValue>
        <fullName>APM</fullName>
    </customValue>
    <customValue>
        <fullName>BACS</fullName>
    </customValue>
    <customValue>
        <fullName>Bancolombia</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Card</fullName>
    </customValue>
    <customValue>
        <fullName>Daviplata</fullName>
    </customValue>
    <customValue>
        <fullName>Davivienda PSE</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <customValue>
        <fullName>Efecty</fullName>
    </customValue>
    <customValue>
        <fullName>EFT</fullName>
    </customValue>
    <customValue>
        <fullName>ELP/Hiper/Amex</fullName>
    </customValue>
    <customValue>
        <fullName>FX Cards</fullName>
    </customValue>
    <customValue>
        <fullName>Ideal</fullName>
    </customValue>
    <customValue>
        <fullName>Interac</fullName>
    </customValue>
    <customValue>
        <fullName>JCB</fullName>
    </customValue>
    <customValue>
        <fullName>MC/Visa</fullName>
    </customValue>
    <customValue>
        <fullName>MC/Visa Credit</fullName>
    </customValue>
    <customValue>
        <fullName>MC/Visa Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Nequi</fullName>
    </customValue>
    <customValue>
        <fullName>Online Bank Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>OXXO</fullName>
    </customValue>
    <customValue>
        <fullName>Pago Efectivo</fullName>
    </customValue>
    <customValue>
        <fullName>Pagos</fullName>
    </customValue>
    <customValue>
        <fullName>Paynet</fullName>
    </customValue>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

FLY wire David/force-app/main/default/globalValueSets/Transaction_Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <description>Transaction currencies used in CPQ Quoting. Not invoice currency</description>
    <masterLabel>Transaction Currencies</masterLabel>
</GlobalValueSet>

FLY wire David/review/SALDEV-1467-org-review/force-app/main/default/classes/QuoteLineTriggerHandler.cls
public with sharing class QuoteLineTriggerHandler {

    public static Boolean isFirstRun = true;

 // =========================================================================
    // SALDEV-1499: QUOTE LINE BACKGROUND FIELD & RATE DETAILS AUTOMATION
    // =========================================================================
    /**
     * SALDEV-1499: Replaces 'Quote Line Type background field update' Flow.
     * Populates Quote_Line_Type_background__c and Rate_Details_Changed__c in memory on before insert/update.
     * Prevents SOQL 101 Governor Limit exceptions and cascades caused by after-save Flow DML updates.
     */
 public static void processBackgroundFields(List<SBQQ__QuoteLine__c> newLines, Map<Id, SBQQ__QuoteLine__c> oldMap) {
    if (newLines == null || newLines.isEmpty()) return;

    Set<Id> sourceLineIds = new Set<Id>();
    Set<Id> subscriptionIds = new Set<Id>();

    for (SBQQ__QuoteLine__c ql : newLines) {
        if (ql == null) continue;
        if (ql.SBQQ__Source__c != null) {
            sourceLineIds.add(ql.SBQQ__Source__c);
        }
        if (ql.SBQQ__UpgradedSubscription__c != null) {
            subscriptionIds.add(ql.SBQQ__UpgradedSubscription__c);
        }
        if (ql.SBQQ__RenewedSubscription__c != null) {
            subscriptionIds.add(ql.SBQQ__RenewedSubscription__c);
        }
    }

    // Query Source Line baselines safely
    Map<Id, SBQQ__QuoteLine__c> sourceLineMap = new Map<Id, SBQQ__QuoteLine__c>();
    if (!sourceLineIds.isEmpty()) {
        sourceLineMap = new Map<Id, SBQQ__QuoteLine__c>([
            SELECT Id, Rate_Details__c, Default_Rate_Details__c
            FROM SBQQ__QuoteLine__c
            WHERE Id IN :sourceLineIds
        ]);
    }

    // Query Subscription baselines safely
    Map<Id, SBQQ__Subscription__c> subMap = new Map<Id, SBQQ__Subscription__c>();
    if (!subscriptionIds.isEmpty()) {
        subMap = new Map<Id, SBQQ__Subscription__c>([
            SELECT Id, Rate_Details__c
            FROM SBQQ__Subscription__c
            WHERE Id IN :subscriptionIds
        ]);
    }

    for (SBQQ__QuoteLine__c ql : newLines) {
        if (ql == null) continue;

        String currentRateDetails = String.isNotBlank(ql.Rate_Details__c) ? ql.Rate_Details__c.trim() : '';
        String defaultRateDetails = String.isNotBlank(ql.Default_Rate_Details__c) ? ql.Default_Rate_Details__c.trim() : '';

        // 1. BASELINE FALLBACK (Null-Guarded)
        if (String.isBlank(defaultRateDetails)) {
            if (ql.SBQQ__Source__c != null && sourceLineMap.containsKey(ql.SBQQ__Source__c)) {
                SBQQ__QuoteLine__c src = sourceLineMap.get(ql.SBQQ__Source__c);
                if (src != null) {
                    defaultRateDetails = String.isNotBlank(src.Default_Rate_Details__c)
                        ? src.Default_Rate_Details__c.trim()
                        : (String.isNotBlank(src.Rate_Details__c) ? src.Rate_Details__c.trim() : '');
                }
            } else if (ql.SBQQ__UpgradedSubscription__c != null && subMap.containsKey(ql.SBQQ__UpgradedSubscription__c)) {
                SBQQ__Subscription__c sub = subMap.get(ql.SBQQ__UpgradedSubscription__c);
                if (sub != null && String.isNotBlank(sub.Rate_Details__c)) {
                    defaultRateDetails = sub.Rate_Details__c.trim();
                }
            } else if (ql.SBQQ__RenewedSubscription__c != null && subMap.containsKey(ql.SBQQ__RenewedSubscription__c)) {
                SBQQ__Subscription__c sub = subMap.get(ql.SBQQ__RenewedSubscription__c);
                if (sub != null && String.isNotBlank(sub.Rate_Details__c)) {
                    defaultRateDetails = sub.Rate_Details__c.trim();
                }
            }

            if (String.isNotBlank(defaultRateDetails)) {
                ql.Default_Rate_Details__c = defaultRateDetails;
            }
        }

        // 2. RATE MISMATCH CHECK
        boolean isBaselineMismatch = false;
        if (String.isNotBlank(defaultRateDetails)) {
            isBaselineMismatch = (currentRateDetails != defaultRateDetails);
        } else if (String.isNotBlank(currentRateDetails)) {
            isBaselineMismatch = true;
        }

        // FINAL ASSIGNMENT (Strictly tracking Rate Details text change)
        ql.Rate_Details_Changed__c = isBaselineMismatch;

        if (String.isNotBlank(ql.Quote_Line_Type__c)) {
            ql.Quote_Line_Type_background__c = ql.Quote_Line_Type__c;
        }
    }
}
    // =========================================================================
    // SALDEV-1427/1467/1499: AMENDMENT CLONE & PRICE CHANGE HANDLING
    // =========================================================================

    /**
     * Evaluates Amendment lines during before insert and before update.
     * Pass 1: Evaluates parent and standalone lines first.
     * Pass 2: Child option lines inherit Price_Change__c directly from their specific parent bundle.
     */
    public static void handlePriceChangeOnAmendmentClones(List<SBQQ__QuoteLine__c> records) {
        if (records == null || records.isEmpty()) return;

        Set<Id> quoteIds = new Set<Id>();
        Set<Id> sourceLineIds = new Set<Id>();
        Set<Id> requiredByParentIds = new Set<Id>();

        for (SBQQ__QuoteLine__c ql : records) {
            if (ql.SBQQ__Quote__c != null) {
                quoteIds.add(ql.SBQQ__Quote__c);
            }
            if (ql.SBQQ__Source__c != null) {
                sourceLineIds.add(ql.SBQQ__Source__c);
            }
            if (ql.SBQQ__RequiredBy__c != null) {
                requiredByParentIds.add(ql.SBQQ__RequiredBy__c);
            }
        }

        Map<Id, SBQQ__Quote__c> quoteMap = new Map<Id, SBQQ__Quote__c>();
        if (!quoteIds.isEmpty()) {
            quoteMap = new Map<Id, SBQQ__Quote__c>([
                SELECT Id, SBQQ__Type__c 
                FROM SBQQ__Quote__c 
                WHERE Id IN :quoteIds
            ]);
        }

        // Query source lines to compare configuration attributes directly
        Map<Id, SBQQ__QuoteLine__c> sourceLineMap = new Map<Id, SBQQ__QuoteLine__c>();
        if (!sourceLineIds.isEmpty()) {
            sourceLineMap = new Map<Id, SBQQ__QuoteLine__c>([
                SELECT Id, SBQQ__Product__c, Ship_To_Account__c, Attribute_Code__c, Payment_Method__c, Transaction_Currency__c
                FROM SBQQ__QuoteLine__c
                WHERE Id IN :sourceLineIds
            ]);
        }

        // Query parent bundle line details
        Map<Id, SBQQ__QuoteLine__c> parentBundleMap = new Map<Id, SBQQ__QuoteLine__c>();
        if (!requiredByParentIds.isEmpty()) {
            parentBundleMap = new Map<Id, SBQQ__QuoteLine__c>([
                SELECT Id, Price_Change__c, SBQQ__Quantity__c, SBQQ__Product__c 
                FROM SBQQ__QuoteLine__c 
                WHERE Id IN :requiredByParentIds
            ]);
        }

        // Map active replacement lines using full configuration composite keys
        Map<Id, Set<String>> activeReplacementsByQuote = new Map<Id, Set<String>>();
        if (!quoteIds.isEmpty()) {
            for (SBQQ__QuoteLine__c ql : [
                SELECT Id, SBQQ__Quote__c, SBQQ__Product__c, SBQQ__Quantity__c, SBQQ__UpgradedSubscription__c, SBQQ__Source__c,
                       Ship_To_Account__c, Attribute_Code__c, Payment_Method__c, Transaction_Currency__c, SBQQ__RequiredBy__c
                FROM SBQQ__QuoteLine__c 
                WHERE SBQQ__Quote__c IN :quoteIds
                  AND SBQQ__Quantity__c > 0
                  AND SBQQ__Product__c != NULL
            ]) {
                if (ql.SBQQ__Source__c != null || ql.SBQQ__UpgradedSubscription__c == null) {
                    String matchKey = buildFullConfigKey(
                        (String)ql.SBQQ__Product__c, 
                        (String)ql.Ship_To_Account__c, 
                        (String)ql.Attribute_Code__c, 
                        (String)ql.Payment_Method__c, 
                        (String)ql.Transaction_Currency__c
                    );
                    if (!activeReplacementsByQuote.containsKey(ql.SBQQ__Quote__c)) {
                        activeReplacementsByQuote.put(ql.SBQQ__Quote__c, new Set<String>());
                    }
                    activeReplacementsByQuote.get(ql.SBQQ__Quote__c).add(matchKey);
                }
            }
        }

        // In-memory status store for parent records processed in the current batch
        Map<Id, Boolean> parentCalculatedPriceChangeMap = new Map<Id, Boolean>();

        // -------------------------------------------------------------------------
        // PASS 1: EVALUATE PARENT AND STANDALONE LINES FIRST
        // -------------------------------------------------------------------------
        for (SBQQ__QuoteLine__c ql : records) {
            SBQQ__Quote__c parentQuote = quoteMap.get(ql.SBQQ__Quote__c);
            Boolean isAmendmentQuote = (parentQuote != null && parentQuote.SBQQ__Type__c == 'Amendment');

            if (isAmendmentQuote && ql.SBQQ__RequiredBy__c == null) {
                String currentLineMatchKey = buildFullConfigKey(
                    (String)ql.SBQQ__Product__c, 
                    (String)ql.Ship_To_Account__c, 
                    (String)ql.Attribute_Code__c, 
                    (String)ql.Payment_Method__c, 
                    (String)ql.Transaction_Currency__c
                );
                
                Set<String> activeReplacements = activeReplacementsByQuote.get(ql.SBQQ__Quote__c);
                Boolean hasMatchingReplacement = (activeReplacements != null && activeReplacements.contains(currentLineMatchKey));

                Boolean isClonedWithConfigChange = false;
                if (ql.SBQQ__Source__c != null && sourceLineMap.containsKey(ql.SBQQ__Source__c)) {
                    SBQQ__QuoteLine__c srcLine = sourceLineMap.get(ql.SBQQ__Source__c);
                    if (ql.Payment_Method__c != srcLine.Payment_Method__c ||
                        ql.Transaction_Currency__c != srcLine.Transaction_Currency__c ||
                        ql.Attribute_Code__c != srcLine.Attribute_Code__c ||
                        ql.Ship_To_Account__c != srcLine.Ship_To_Account__c) {
                        isClonedWithConfigChange = true;
                    }
                }

                if (ql.SBQQ__UpgradedSubscription__c == null && (ql.SBQQ__Source__c == null || isClonedWithConfigChange)) {
                    ql.Price_Change__c = false;
                } else if (ql.SBQQ__UpgradedSubscription__c == null && ql.SBQQ__Source__c != null && !isClonedWithConfigChange) {
                    ql.Price_Change__c = true;
                } else if (ql.SBQQ__UpgradedSubscription__c != null && ql.SBQQ__Quantity__c == 0) {
                    ql.Price_Change__c = (hasMatchingReplacement && !isClonedWithConfigChange);
                } else if (ql.SBQQ__UpgradedSubscription__c != null && ql.SBQQ__Quantity__c > 0) {
                    ql.Price_Change__c = false;
                }

                if (ql.Id != null) {
                    parentCalculatedPriceChangeMap.put(ql.Id, ql.Price_Change__c);
                }
            }
        }

        // -------------------------------------------------------------------------
        // PASS 2: EVALUATE CHILD OPTION LINES AGAINST SPECIFIC PARENT CONTEXT
        // -------------------------------------------------------------------------
        for (SBQQ__QuoteLine__c ql : records) {
            SBQQ__Quote__c parentQuote = quoteMap.get(ql.SBQQ__Quote__c);
            Boolean isAmendmentQuote = (parentQuote != null && parentQuote.SBQQ__Type__c == 'Amendment');

            if (isAmendmentQuote && ql.SBQQ__RequiredBy__c != null) {
                Boolean parentPriceChange = false;
                if (parentCalculatedPriceChangeMap.containsKey(ql.SBQQ__RequiredBy__c)) {
                    parentPriceChange = parentCalculatedPriceChangeMap.get(ql.SBQQ__RequiredBy__c);
                } else if (parentBundleMap.containsKey(ql.SBQQ__RequiredBy__c)) {
                    parentPriceChange = (parentBundleMap.get(ql.SBQQ__RequiredBy__c).Price_Change__c == true);
                }

                if (ql.SBQQ__UpgradedSubscription__c == null && ql.SBQQ__Source__c != null) {
                    ql.Price_Change__c = true; // Formula outputs 'Price Change'
                } else if (ql.SBQQ__UpgradedSubscription__c != null && ql.SBQQ__Quantity__c == 0) {
                    ql.Price_Change__c = parentPriceChange; // false -> 'Cancellation', true -> 'Cancellation Price Change'
                } else {
                    ql.Price_Change__c = false;
                }
            }
        }
    }

    private static String buildFullConfigKey(String prodId, String shipTo, String attrCode, String payMethod, String curr) {
        String p = String.isNotBlank(prodId) ? prodId : '';
        String s = String.isNotBlank(shipTo) ? shipTo : '';
        String a = String.isNotBlank(attrCode) ? attrCode : '';
        String pm = String.isNotBlank(payMethod) ? payMethod : '';
        String c = String.isNotBlank(curr) ? curr : '';
        return p + '-' + s + '-' + a + '-' + pm + '-' + c;
    }

    /**
     * SALDEV-1427/1467: Maps Group 1 Opportunity_Line_Id__c across ramped groups/cloned lines.
     * Uses sequential group positioning per product, completely independent of SBQQ__Source__c.
     */
    public static void copyOpportunityLineIdOnRamp(List<SBQQ__QuoteLine__c> newRecords) {
        if (newRecords == null || newRecords.isEmpty()) return;

        try {
            Set<Id> quoteIds = new Set<Id>();
            for (SBQQ__QuoteLine__c ql : newRecords) {
                if (ql.SBQQ__Quote__c != null) {
                    quoteIds.add(ql.SBQQ__Quote__c);
                }
            }

            // 1. Fetch Group 1 Master IDs ordered by creation/sequence
            Map<String, List<String>> group1OrderedIdsMap = new Map<String, List<String>>();

            if (!quoteIds.isEmpty()) {
                for (SBQQ__QuoteLine__c ql : [
                    SELECT Id, SBQQ__Quote__c, SBQQ__Product__c, Opportunity_Line_Id__c, 
                           SBQQ__Group__r.SBQQ__Number__c
                    FROM SBQQ__QuoteLine__c 
                    WHERE SBQQ__Quote__c IN :quoteIds 
                      AND Opportunity_Line_Id__c != NULL
                    ORDER BY SBQQ__Group__r.SBQQ__Number__c ASC NULLS FIRST, CreatedDate ASC, Id ASC
                ]) {
                    String prodKey = ql.SBQQ__Quote__c + '-' + ql.SBQQ__Product__c;
                    if (!group1OrderedIdsMap.containsKey(prodKey)) {
                        group1OrderedIdsMap.put(prodKey, new List<String>());
                    }
                    group1OrderedIdsMap.get(prodKey).add(ql.Opportunity_Line_Id__c);
                }
            }

            Map<String, Integer> productOccurrenceCounter = new Map<String, Integer>();

            // 2. Assign Opportunity_Line_Id__c based strictly on sequential slot position
            for (SBQQ__QuoteLine__c ql : newRecords) {
                if (ql.SBQQ__Product__c == null) continue;

                String prodKey = ql.SBQQ__Quote__c + '-' + ql.SBQQ__Product__c;
                Integer currentSlot = productOccurrenceCounter.containsKey(prodKey) 
                    ? productOccurrenceCounter.get(prodKey) 
                    : 0;

                // Inherit from Group 1 Master slot position if unassigned
                if (ql.Opportunity_Line_Id__c == null && group1OrderedIdsMap.containsKey(prodKey)) {
                    List<String> masterIds = group1OrderedIdsMap.get(prodKey);
                    if (currentSlot < masterIds.size()) {
                        ql.Opportunity_Line_Id__c = masterIds.get(currentSlot);
                    } else {
                        ql.Opportunity_Line_Id__c = masterIds.get(0); // Fallback to primary slot
                    }
                }

                productOccurrenceCounter.put(prodKey, currentSlot + 1);
            }

        } catch (Exception e) {
            System.debug('Error in copyOpportunityLineIdOnRamp: ' + e.getMessage() + ' at line ' + e.getLineNumber());
        }
    }

    // =========================================================================
    // QUOTE LINE ROLLUP & AVERAGE PRICE CALCULATION ENGINE
    // =========================================================================

    public class RollupMapping {
        public String baseField;
        public String rollupField;
        public String operation;
        public String alias;

        public RollupMapping(String baseField, String rollupField, String operation, String alias) {
            this.baseField = baseField;
            this.rollupField = rollupField;
            this.operation = operation;
            this.alias = alias;
        }
    }

    @TestVisible 
    private static List<RollupMapping> mockRollupMappings;

    private static List<RollupMapping> getRollupMappings() {
        if (mockRollupMappings != null) return mockRollupMappings;

        List<RollupMapping> mappings = new List<RollupMapping>();
        Integer aliasCounter = 0;

        for (Quote_Line_Rollup_Field_Mapping__mdt cmdt : Quote_Line_Rollup_Field_Mapping__mdt.getAll().values()) {
            if (String.isNotBlank(cmdt.Field__c) && 
                String.isNotBlank(cmdt.Rollup_Field__c) && 
                String.isNotBlank(cmdt.Type_of_Operation__c)) {
                
                mappings.add(new RollupMapping(
                    cmdt.Field__c, 
                    cmdt.Rollup_Field__c, 
                    cmdt.Type_of_Operation__c,
                    'alias' + aliasCounter 
                ));
                aliasCounter++;
            }
        }
        return mappings;
    }

    public static void calculateAveragePrice(List<SBQQ__QuoteLine__c> records, Map<Id, SBQQ__QuoteLine__c> oldMap) {
        if (records == null || records.isEmpty()) return;

        try {
            List<RollupMapping> fieldMappings = getRollupMappings();
            if (fieldMappings.isEmpty()) return;

            Set<Id> quoteIds = new Set<Id>();

            for (SBQQ__QuoteLine__c ql : records) {
                if (oldMap == null) {
                    quoteIds.add(ql.SBQQ__Quote__c);
                } else {
                    SBQQ__QuoteLine__c oldQl = oldMap.get(ql.Id);
                    Boolean isChanged = (ql.SBQQ__Product__c != oldQl.SBQQ__Product__c || 
                                         ql.SBQQ__StartDate__c != oldQl.SBQQ__StartDate__c);
                    
                    if (!isChanged) {
                        for (RollupMapping mapping : fieldMappings) {
                            if (ql.get(mapping.baseField) != oldQl.get(mapping.baseField)) {
                                isChanged = true;
                                break;
                            }
                        }
                    }

                    if (isChanged) {
                        quoteIds.add(ql.SBQQ__Quote__c);
                    }
                }
            }

            if (quoteIds.isEmpty()) return;

            String aggQuery = 'SELECT SBQQ__Quote__c, SBQQ__Product__c';
            for (RollupMapping mapping : fieldMappings) {
                String soqlFunction;
                if (mapping.operation.equalsIgnoreCase('Average')) {
                    soqlFunction = 'AVG';
                } else if (mapping.operation.equalsIgnoreCase('Sum')) {
                    soqlFunction = 'SUM';
                } else if (mapping.operation.equalsIgnoreCase('Min')) {
                    soqlFunction = 'MIN';
                } else if (mapping.operation.equalsIgnoreCase('Max')) {
                    soqlFunction = 'MAX';
                } 
                
                aggQuery += ', ' + soqlFunction + '(' + mapping.baseField + ') ' + mapping.alias;
            }
            aggQuery += ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c IN :quoteIds AND SBQQ__Product__c != null GROUP BY SBQQ__Quote__c, SBQQ__Product__c';
            
            List<AggregateResult> aggResults = Database.query(aggQuery);

            Map<String, Map<String, Decimal>> rollupDataMap = new Map<String, Map<String, Decimal>>();
            for (AggregateResult ar : aggResults) {
                String key = (Id)ar.get('SBQQ__Quote__c') + '-' + (Id)ar.get('SBQQ__Product__c');
                Map<String, Decimal> calculatedRollups = new Map<String, Decimal>();
                
                for (RollupMapping mapping : fieldMappings) {
                    calculatedRollups.put(mapping.rollupField, (Decimal)ar.get(mapping.alias));
                }
                rollupDataMap.put(key, calculatedRollups);
            }

            String sortQuery = 'SELECT Id, SBQQ__Quote__c, SBQQ__Product__c, SBQQ__StartDate__c';
            for (RollupMapping mapping : fieldMappings) {
                sortQuery += ', ' + mapping.rollupField;
            }
            sortQuery += ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c IN :quoteIds AND SBQQ__Product__c != null ORDER BY SBQQ__Quote__c, SBQQ__Product__c, SBQQ__StartDate__c ASC NULLS LAST';
            
            List<SBQQ__QuoteLine__c> linesToProcess = Database.query(sortQuery);

            Set<String> processedKeys = new Set<String>();
            Map<Id, SBQQ__QuoteLine__c> recordsToUpdate = new Map<Id, SBQQ__QuoteLine__c>();

            for (SBQQ__QuoteLine__c ql : linesToProcess) {
                String key = ql.SBQQ__Quote__c + '-' + ql.SBQQ__Product__c;
                SBQQ__QuoteLine__c updateObj = new SBQQ__QuoteLine__c(Id = ql.Id);
                Boolean fieldChanged = false;

                if (!processedKeys.contains(key)) {
                    processedKeys.add(key); 
                    
                    Map<String, Decimal> rollups = rollupDataMap.get(key);
                    if (rollups != null) {
                        for (RollupMapping mapping : fieldMappings) {
                            Decimal calculatedValue = rollups.get(mapping.rollupField);
                            if (ql.get(mapping.rollupField) != calculatedValue) {
                                updateObj.put(mapping.rollupField, calculatedValue);
                                fieldChanged = true;
                            }
                        }
                    }
                } else {
                    for (RollupMapping mapping : fieldMappings) {
                        if (ql.get(mapping.rollupField) != null) {
                            updateObj.put(mapping.rollupField, null);
                            fieldChanged = true;
                        }
                    }
                }

                if (fieldChanged) {
                    recordsToUpdate.put(ql.Id, updateObj);
                }
            }

            if (!recordsToUpdate.isEmpty()) {
                Database.update(recordsToUpdate.values(), false);
            }

        } catch (Exception e) {
            System.debug('Error in QuoteLineTriggerHandler: ' + e.getMessage() + ' on line ' + e.getLineNumber());
            for (SBQQ__QuoteLine__c ql : records) {
                ql.addError('An error occurred calculating Quote Line rollups: ' + e.getMessage());
            }
        }
    }
}